import { createHash } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { Resend, type EmailReceivedEvent } from "resend";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { parseHeaderReferences, sanitizeMailHtml, textFromHtml } from "@/lib/mail/security";

export const runtime = "nodejs";
const allowedAttachments = new Set(["application/pdf", "image/jpeg", "image/png", "image/webp", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/plain"]);
function emailOnly(value: string) { return (value.match(/<([^>]+)>/)?.[1] || value).trim().toLowerCase(); }
function address(value: string) { const email = emailOnly(value); const name = value.includes("<") ? value.slice(0, value.lastIndexOf("<")).trim().replace(/^['"]|['"]$/g, "") : ""; return { email, ...(name ? { name } : {}) }; }

export async function POST(request: NextRequest) {
  const secret = process.env.RESEND_WEBHOOK_SECRET?.trim(); const apiKey = process.env.RESEND_API_KEY?.trim();
  if (!secret || !apiKey) return NextResponse.json({ error: "Webhook no configurado." }, { status: 503 });
  const payload = await request.text(); const eventId = request.headers.get("svix-id") || ""; const timestamp = request.headers.get("svix-timestamp") || ""; const signature = request.headers.get("svix-signature") || "";
  if (!eventId || !timestamp || !signature) return NextResponse.json({ error: "Firma requerida." }, { status: 400 });
  const resend = new Resend(apiKey); let event;
  try { event = resend.webhooks.verify({ payload, headers: { id: eventId, timestamp, signature }, webhookSecret: secret }); } catch { return NextResponse.json({ error: "Firma inválida." }, { status: 401 }); }
  const client = createSupabaseAdminClient(); const hash = createHash("sha256").update(payload).digest("hex");
  const insertedEvent = await client.from("mail_webhook_events").insert({ provider_event_id: eventId, event_type: event.type, payload_hash: hash }).select("status").maybeSingle();
  if (insertedEvent.error?.code === "23505") { const { data: existing } = await client.from("mail_webhook_events").select("status,payload_hash").eq("provider_event_id", eventId).single(); if (!existing) return NextResponse.json({ error: "No pudimos validar el evento." }, { status: 500 }); if (existing.payload_hash !== hash) return NextResponse.json({ error: "Evento inconsistente." }, { status: 409 }); if (existing.status === "processed" || existing.status === "ignored") return NextResponse.json({ ok: true, duplicate: true }); }
  if (event.type !== "email.received") { await client.from("mail_webhook_events").update({ status: "ignored", processed_at: new Date().toISOString() }).eq("provider_event_id", eventId); return NextResponse.json({ ok: true, ignored: true }); }
  try {
    const receivedEvent = event as EmailReceivedEvent; const received = await resend.emails.receiving.get(receivedEvent.data.email_id); if (received.error || !received.data) throw new Error("provider_retrieve_failed");
    const recipientEmails = received.data.to.map(emailOnly); const { data: identities } = await client.from("mail_identities").select("id,email").in("email", recipientEmails).eq("status", "active");
    const identity = identities?.[0]; if (!identity) { await client.from("mail_webhook_events").update({ status: "ignored", processed_at: new Date().toISOString() }).eq("provider_event_id", eventId); return NextResponse.json({ ok: true, ignored: true }); }
    const headers = Object.fromEntries(Object.entries(received.data.headers || {}).map(([key, value]) => [key.toLowerCase(), value])); const inReplyTo = headers["in-reply-to"] || null; const references = parseHeaderReferences(headers.references);
    let threadId: string | null = null;
    if (inReplyTo) { const { data: parent } = await client.from("mail_messages").select("thread_id").eq("message_id", inReplyTo).maybeSingle(); threadId = parent?.thread_id || null; }
    if (!threadId && references.length) { const { data: parent } = await client.from("mail_messages").select("thread_id").in("message_id", references).order("created_at", { ascending: false }).limit(1).maybeSingle(); threadId = parent?.thread_id || null; }
    const rawHtml = received.data.html || `<p>${(received.data.text || "").replace(/[&<>]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[character] || character)).replace(/\n/g, "<br>")}</p>`; const hasRemoteImages = /<img\b[^>]*\bsrc\s*=\s*["']https?:/i.test(rawHtml); const cleanHtml = sanitizeMailHtml(rawHtml); const cleanText = (received.data.text || textFromHtml(cleanHtml)).slice(0, 1_000_000); const now = received.data.created_at || new Date().toISOString();
    if (!threadId) { const { data: assignments } = await client.from("mail_identity_assignments").select("profile_id").eq("identity_id", identity.id).eq("active", true).order("is_primary", { ascending: false }).limit(1); const created = await client.from("mail_threads").insert({ identity_id: identity.id, subject: received.data.subject || "(Sin asunto)", assigned_to: assignments?.[0]?.profile_id || null, snippet: cleanText.slice(0, 500), latest_message_at: now }).select("id").single(); if (created.error) throw created.error; threadId = created.data.id; }
    const message = await client.from("mail_messages").insert({ thread_id: threadId, direction: "inbound", delivery_status: "received", provider_email_id: received.data.id, provider_event_id: eventId, message_id: received.data.message_id, in_reply_to: inReplyTo, reference_ids: references, from_address: address(received.data.from), to_addresses: received.data.to.map(address), cc_addresses: (received.data.cc || []).map(address), bcc_addresses: (received.data.bcc || []).map(address), subject: received.data.subject || "(Sin asunto)", body_html: cleanHtml, body_text: cleanText, has_remote_images: hasRemoteImages, received_at: now }).select("id").single(); if (message.error) { if (message.error.code === "23505") { await client.from("mail_webhook_events").update({ status: "processed", processed_at: new Date().toISOString() }).eq("provider_event_id", eventId); return NextResponse.json({ ok: true, duplicate: true }); } throw message.error; }
    await client.from("mail_threads").update({ state: "inbox", subject: received.data.subject || "(Sin asunto)", snippet: cleanText.slice(0, 500), latest_message_at: now, updated_at: new Date().toISOString() }).eq("id", threadId);
    const attachmentList = await resend.emails.receiving.attachments.list({ emailId: received.data.id });
    for (const attachment of attachmentList.data?.data || []) { if (!allowedAttachments.has(attachment.content_type) || attachment.size > 10 * 1024 * 1024) continue; const download = await fetch(attachment.download_url); if (!download.ok) continue; const path = `${identity.id}/${threadId}/${crypto.randomUUID()}`; const uploaded = await client.storage.from("mail-attachments").upload(path, new Uint8Array(await download.arrayBuffer()), { contentType: attachment.content_type, upsert: false }); if (!uploaded.error) await client.from("mail_attachments").insert({ message_id: message.data.id, provider_attachment_id: attachment.id, storage_path: path, filename: (attachment.filename || "archivo").replace(/[\r\n]/g, "").slice(0, 255), content_type: attachment.content_type, size_bytes: attachment.size, content_id: attachment.content_id || null, inline: attachment.content_disposition === "inline" }); }
    const { data: assignees } = await client.from("mail_identity_assignments").select("profile_id,profiles(email,display_name,name)").eq("identity_id", identity.id).eq("active", true); for (const assignment of assignees || []) { const profile = Array.isArray(assignment.profiles) ? assignment.profiles[0] : assignment.profiles; await client.from("mail_read_states").upsert({ thread_id: threadId, profile_id: assignment.profile_id, unread: true, last_read_at: now }); await client.from("notifications").insert({ firebase_id: `mail:${eventId}:${assignment.profile_id}`, recipient_id: assignment.profile_id, recipient_name: profile?.display_name || profile?.name || "", recipient_email: profile?.email || "", type: "mail_received", severity: "info", title: "Nuevo correo recibido", message: `Nuevo mensaje en ${identity.email}`, action_url: `/admin/mail?thread=${threadId}`, is_read: false, created_at: now, updated_at: now }); }
    await client.from("mail_audit_events").insert({ action: "mail_message_received", identity_id: identity.id, thread_id: threadId, message_id: message.data.id, safe_metadata: { provider: "resend", attachmentCount: attachmentList.data?.data.length || 0 } }); await client.from("mail_webhook_events").update({ status: "processed", processed_at: new Date().toISOString() }).eq("provider_event_id", eventId);
    return NextResponse.json({ ok: true });
  } catch (error) { await client.from("mail_webhook_events").update({ status: "failed", error_category: error instanceof Error ? error.name : "unknown" }).eq("provider_event_id", eventId); return NextResponse.json({ error: "No pudimos procesar el evento." }, { status: 500 }); }
}
