import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { requireAdminFromRequest } from "@/lib/admin/auth";
import { hasPermission } from "@/lib/admin/authorization";
import { financeMutation,financeReport } from "@/lib/finance/data";

const schema=z.object({report:z.enum(["collections","receivables","overdue","expenses","cash_result","project_sales","seller"]),from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),currency:z.enum(["USD","HNL"]).optional(),clientId:z.string().uuid().optional(),projectId:z.string().uuid().optional(),sellerId:z.string().uuid().optional(),paymentMethod:z.enum(["bank_transfer","cash","card","paypal","other"]).optional(),categoryId:z.string().uuid().optional()}).strict();
function safe(value:unknown){let text=String(value??"").replace(/\r?\n/g," ");if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`;}
export async function GET(request:NextRequest){const admin=await requireAdminFromRequest(request);if(!admin)return NextResponse.json({error:"No autorizado."},{status:401});if(!hasPermission(admin,"reports:export"))return NextResponse.json({error:"No tienes permiso para exportar reportes financieros."},{status:403});const raw=Object.fromEntries(request.nextUrl.searchParams.entries());delete raw.period;delete raw.page;const parsed=schema.safeParse(raw);if(!parsed.success)return NextResponse.json({error:"Filtros de exportacion invalidos."},{status:400});try{const rows=[];for(let page=1;page<=25;page+=1){const result=await financeReport({...parsed.data,page,pageSize:200});rows.push(...result.items);if(rows.length>=result.total)break;}await financeMutation("report_exported",{report:parsed.data.report,format:"csv"});const headers=["Fecha","Tipo","Cliente o proveedor","Concepto","Proyecto","Metodo","Importe menor","Moneda","Estado"];const lines=[headers.map(safe).join(","),...rows.map(row=>[row.occurredOn,row.recordType,row.party,row.concept,row.projectName,row.paymentMethod,row.amountMinor,row.currency,row.status].map(safe).join(","))];const filename=`ken-code-${parsed.data.report}-${parsed.data.from}-${parsed.data.to}.csv`;return new NextResponse(`\uFEFF${lines.join("\r\n")}`,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="${filename}"`,"Cache-Control":"private, no-store"}});}catch(error){const status=typeof error==="object"&&error&&"status" in error?Number(error.status):400;return NextResponse.json({error:status===403?"Exportacion no autorizada.":"No se pudo generar la exportacion."},{status});}}
