import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const domain=readFileSync("supabase/migrations/20260901000200_phase4_modules_proposals.sql","utf8");
const billing=readFileSync("supabase/migrations/20260901000300_phase4_billing_finance.sql","utf8");
const origins=readFileSync("supabase/migrations/20260901000100_phase4_receivable_origins.sql","utf8");
const api=readFileSync("src/app/api/admin/add-ons/route.ts","utf8");
const pdf=readFileSync("src/lib/add-ons/proposal-pdf.ts","utf8");
const list=readFileSync("src/components/admin/module-list.tsx","utf8");
const detail=readFileSync("src/components/admin/module-detail.tsx","utf8");
const data=readFileSync("src/lib/add-ons/data.ts","utf8");
const nav=readFileSync("src/components/admin/admin-chrome.tsx","utf8");
const authorization=readFileSync("src/lib/admin/authorization.ts","utf8");
const report=readFileSync("src/components/admin/finance-report-table.tsx","utf8");
const finance=readFileSync("src/components/admin/finance-dashboard.tsx","utf8");
const cases=[
 ["01 module table",domain,/create table public\.project_add_ons/],["02 project FK",domain,/project_id uuid not null references public\.projects/],["03 client FK",domain,/client_id uuid not null references public\.clients/],["04 USD default",domain,/currency text not null default 'USD'/],["05 HNL rejected DB",domain,/module currency must be USD/],["06 EUR rejected server",api,/z\.literal\("USD"\)/],["07 seller field",domain,/assigned_sales_agent_id uuid/],["08 commercial states",domain,/requested.*quoting.*proposal_sent.*approved.*rejected.*cancelled/s],["09 work states",domain,/pending.*scheduled.*in_progress.*ready.*delivered/s],
 ["10 proposal draft",domain,/add_on_proposal_status as enum \('draft'/],["11 versions",domain,/unique\(add_on_id,version\)/],["12 superseded preservation",domain,/status='superseded'/],["13 sent explicit",domain,/proposal_mark_sent/],["14 accepted",domain,/status='accepted'/],["15 rejected",domain,/status='rejected'/],["16 double accept denied",domain,/module already approved/],["17 accepted immutable",domain,/historical proposal terms are immutable/],["18 notes separated",domain,/client_notes text.*internal_notes text/s],["19 human number sequence",domain,/next_add_on_proposal_number/],["20 PDF structure",pdf,/Cliente.*Proyecto.*Modulo o ampliacion.*Alcance.*Inversion/s],["21 PDF excludes internal notes",pdf,/proposal\.clientNotes/],
 ["22 one payment supported",detail,/Pago unico/],["23 two payments supported",domain,/jsonb_array_elements/],["24 three payments supported",api,/max\(100\)/],["25 custom amounts",api,/amountMinor:minor/],["26 custom dates",api,/dueDate/],["27 due time optional",api,/dueTime/],["28 month split not hardcoded",detail,/Agregar/],["29 sum mismatch rejected",domain,/installment total must equal accepted add-on price/],["30 zero amount rejected",domain,/amount_minor>0/],["31 negative rejected",domain,/amount_minor>0/],["32 activation transaction RPC",domain,/elsif p_operation='payment_plan_activate'/],["33 unique active plan",domain,/add_on_payment_plans_one_active/],
 ["34 one receivable per installment",domain,/unique index receivables_add_on_installment_origin_idx/],["35 idempotent receivable insert",domain,/on conflict\(add_on_installment_id\).*do nothing/s],["36 correct origin",origins,/add_on_installment/],["37 project total unchanged",billing,/original_project_minor/],["38 outstanding mapped",data,/outstandingMinor/],["39 partial payment reused",billing,/payment_allocations/],["40 allocation engine not duplicated",billing,/payment_allocations/],["41 receivables engine reused",domain,/insert into public\.receivables/],["42 reversal remains external",domain,/add_on_installment_id/],["43 reminders reused",billing,/notifications_enabled/],
 ["44 monthly optional",domain,/monthly_add_on_minor bigint not null default 0/],["45 recurring amount positive",domain,/monthly_amount_minor bigint not null check/],["46 base separate",billing,/project_recurring_services/],["47 add-on recurring separate",billing,/add_on_recurring_services/],["48 recurring generator reused",billing,/billing_generate_recurring/],["49 recurring period dedupe",domain,/receivables_add_on_recurring_period_idx/],["50 recurring status",domain,/draft.*active.*paused.*cancelled/],
 ["51 original sales metric",billing,/original_project_sales_minor/],["52 module sales metric",billing,/add_on_sales_minor/],["53 lifetime sold",billing,/lifetime_sold_minor/],["54 module collected",billing,/add_on_collected_minor/],["55 module outstanding",billing,/add_on_outstanding_minor/],["56 base recurring metric",billing,/base_recurring_collected_minor/],["57 module recurring metric",billing,/add_on_recurring_collected_minor/],["58 finance composition UI",finance,/Composicion comercial/],["59 report module sales",report,/module_sales/],["60 USD reports",billing,/p_currency.*USD/],
 ["61 Owner permissions",authorization,/owner: ADMIN_PERMISSIONS/],["62 Admin manage",authorization,/modules:manage/],["63 Sales drafts",authorization,/modules:draft/],["64 Sales RLS scoped",domain,/private\.project_in_current_scope/],["65 Sales no finance",authorization,/sales_agent:[\s\S]*modules:draft/],["66 inactive denied",billing,/private\.current_profile_role\(\)/],["67 Viewer read only",authorization,/viewer:.*modules:view/],["68 Manager conservative",authorization,/manager:.*modules:view/],
 ["69 320 mobile cards",list,/md:hidden/],["70 360 touch targets",detail,/min-h-11/],["71 375 responsive grid",detail,/sm:grid-cols/],["72 390 modal viewport",list,/kc-modal-viewport/],["73 412 no wide table mobile",list,/hidden.*md:block/],["74 430 tabs scroll",detail,/kc-scroll-tabs/],["75 768 list table",list,/md:block/],["76 820 flexible columns",detail,/minmax\(0,1fr\)/],["77 1024 desktop",detail,/lg:grid-cols/],["78 1440 master detail",detail,/xl:grid-cols/],["79 1920 compact",detail,/kc-admin-card/],["80 module list mobile",list,/md:hidden/],["81 detail mobile",detail,/grid gap-5/],["82 proposal builder mobile",detail,/scope/],["83 payment cards mobile",detail,/rounded-2xl border bg-slate-50/],["84 no page overflow",detail,/overflow-x-auto/],
 ["85 global navigation",nav,/\/admin\/modulos/],["86 PDF authenticated route",readFileSync("src/app/api/admin/add-ons/proposals/[id]/pdf/route.ts","utf8"),/requireAdminFromRequest/],["87 PDF no public UUID link",pdf,/proposalNumber/],["88 export audit",domain,/proposal_exported/],["89 no email send",domain,/proposal_mark_sent/],["90 no cron schedule",domain,/create table public\.project_add_ons/],
];
for(const[name,source,pattern]of cases)test(name,()=>assert.match(source,pattern));
test("91 PDF never renders internal notes",()=>assert.doesNotMatch(pdf,/proposal\.internalNotes/));
test("92 migrations send no email",()=>assert.doesNotMatch(domain+billing,/resend|send_email|net\.http_post/i));
test("93 migrations send no push",()=>assert.doesNotMatch(domain+billing,/send_push|fcm/i));
test("94 migrations do not schedule cron",()=>assert.doesNotMatch(domain+billing,/cron\.schedule/i));
test("95 ordinary UI hides implementation terms",()=>{for(const word of ["UUID","RLS","Supabase","Foreign Key","Metadata","Webhook"])assert.doesNotMatch(list+detail,new RegExp(`\\b${word}\\b`,"i"));});
test("96 no fake business data",()=>assert.doesNotMatch(domain,/insert into public\.project_add_ons\s*\([^)]*\)\s*values\s*\('[0-9a-f]/i));


