import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { normalizeLocalPart, sanitizeMailHtml, suggestLocalParts, replySubject, forwardSubject, parseHeaderReferences } from "../src/lib/mail/security.ts";
import { defaultPermissionsForRole } from "../src/lib/admin/authorization.ts";

const files = Object.fromEntries(Object.entries({ shell:"src/components/admin/admin-chrome.tsx", css:"src/app/globals.css", profile:"src/components/admin/profile-panel.tsx", profileApi:"src/app/api/admin/profile/route.ts", profilePhoto:"src/app/api/admin/profile/photo/route.ts", profileMigration:"supabase/migrations/20260902000100_phase5_profiles_shell.sql", mailMigration:"supabase/migrations/20260902000200_phase5_mail_core.sql", privilegeMigration:"supabase/migrations/20260902000300_phase5_mail_service_privileges.sql", hardeningMigration:"supabase/migrations/20260902000400_phase6_mail_delivery_hardening.sql", notificationPrivilegeMigration:"supabase/migrations/20260902000500_phase6_mail_notification_privilege.sql", threadingMigration:"supabase/migrations/20260902000600_phase6_mail_provider_threading.sql", mailUi:"src/components/admin/mail-workspace.tsx", mailApi:"src/app/api/admin/mail/route.ts", identityApi:"src/app/api/admin/mail/identities/route.ts", identityUi:"src/components/admin/mail-identity-manager.tsx", settingsApi:"src/app/api/admin/mail/settings/route.ts", settingsUi:"src/components/admin/mail-settings-manager.tsx", service:"src/lib/mail/service.ts", security:"src/lib/mail/security.ts", webhook:"src/app/api/webhooks/resend/route.ts", attachment:"src/app/api/admin/mail/attachments/route.ts", client:"src/components/admin/client-detail.tsx", lead:"src/components/admin/lead-detail.tsx", project:"src/components/admin/project-detail.tsx", module:"src/components/admin/module-detail.tsx" }).map(([key,path])=>[key,readFileSync(path,"utf8")]));
const cases = [
 ["01 sticky desktop sidebar",files.shell,/sticky top-0.*h-\[100dvh\]/s],["02 sticky app header",files.shell,/kc-admin-header sticky top-0/],["03 single page content owner",files.shell,/min-w-0 pb-/],["04 subtle scrollbar",files.css,/scrollbar-color: rgba/],["05 collapsed hides track",files.css,/is-collapsed::.*scrollbar.*display: none/s],["06 width expanded",files.css,/grid-template-columns: 264px/],["07 width collapsed",files.css,/grid-template-columns: 72px/],["08 preference persists",files.shell,/localStorage\.setItem\(SIDEBAR_STORAGE_KEY/],["09 profile menu button",files.shell,/aria-haspopup="menu"/],["10 menu Escape",files.shell,/event\.key === "Escape"/],["11 menu outside click",files.shell,/mousedown/],["12 same logout endpoint",files.shell,/fetch\("\/api\/admin\/logout"/],["13 sidebar logout",files.shell,/Cerrar sesión/],["14 account menu viewport",files.shell,/calc\(100vw-2rem\)/],["15 long email wrapping",files.shell,/break-all/],["16 mobile safe bottom",files.shell,/safe-area-inset-bottom/],["17 mobile drawer dvh",files.shell,/h-\[100dvh\]/],["18 compact nav rows",files.shell,/min-h-10/],
 ["19 self profile route",files.profileApi,/requireAdminFromRequest/],["20 self exact update",files.profileApi,/eq\("id", admin\.uid\)/],["21 role not accepted",files.profileApi,/profileSchema.*strict/s],["22 active required",files.profileApi,/eq\("active", true\)/],["23 photo MIME allowlist",files.profileApi,/image\/jpeg.*image\/png.*image\/webp/s],["24 photo two MB server",files.profileApi,/2 \* 1024 \* 1024/],["25 photo resize client",files.profile,/512/],["26 photo WebP compression",files.profile,/image\/webp.*0\.84/s],["27 initials fallback",files.profile,/initials/],["28 private bucket",files.profileMigration,/profile-photos','profile-photos',false/],["29 storage size limit",files.profileMigration,/2097152/],["30 storage path per uid",files.profileMigration,/storage\.foldername/],["31 private download auth",files.profilePhoto,/requireAdminFromRequest/],["32 no sniff avatar",files.profilePhoto,/X-Content-Type-Options/],["33 remove old photo",files.profileApi,/storage\.from\("profile-photos"\)\.remove/],
 ["34 mail identity table",files.mailMigration,/create table public\.mail_identities/],["35 user identity separation",files.mailMigration,/mail_identity_assignments/],["36 domain generated",files.mailMigration,/@kencodehn\.com/],["37 identity unique",files.mailMigration,/local_part text not null unique/],["38 reserved identity",files.mailMigration,/abuse.*postmaster.*mailer-daemon/s],["39 assignment history",files.mailMigration,/unassigned_at/],["40 one primary",files.mailMigration,/mail_profile_primary_identity_uq/],["41 inactive preserves identity",files.mailMigration,/on delete restrict/],["42 owner identity capability",files.identityApi,/mail:manage_identities/],["43 explicit confirmation",files.identityApi,/confirmed: z\.literal\(true\)/],["44 normalization server",files.identityApi,/normalizeLocalPart/],["45 active assignment target",files.identityApi,/Solo puede asignar usuarios activos/],["46 audit identity create",files.identityApi,/mail_identity_created/],["47 assignment audit",files.identityApi,/mail_identity_.*ed/],
 ["48 thread table",files.mailMigration,/create table public\.mail_threads/],["49 message table",files.mailMigration,/create table public\.mail_messages/],["50 inbox state",files.mailMigration,/mail_thread_state.*inbox.*archived.*trash/],["51 CRM lead FK",files.mailMigration,/lead_id uuid references public\.leads/],["52 CRM client FK",files.mailMigration,/client_id uuid references public\.clients/],["53 CRM project FK",files.mailMigration,/project_id uuid references public\.projects/],["54 CRM add-on FK",files.mailMigration,/add_on_id uuid references public\.project_add_ons/],["55 CRM proposal FK",files.mailMigration,/proposal_id uuid references public\.add_on_proposals/],["56 messages immutable",files.mailMigration,/mail_messages_immutable/],["57 no hard delete UI",files.mailUi,/Mover a papelera/],["58 per-user read state",files.mailMigration,/primary key\(thread_id,profile_id\)/],["59 follow-up table",files.mailMigration,/create table public\.mail_follow_ups/],["60 cursor index",files.mailMigration,/mail_threads_latest_idx/],["61 message thread index",files.mailMigration,/mail_messages_thread_idx/],["62 server cursor pagination",files.service,/limit\(26\)/],["63 search bounded",files.mailApi,/slice\(0, 120\)/],
 ["64 send permission",files.mailApi,/mail:use/],["65 identity server authorization",files.service,/mayUseIdentity/],["66 rate limit",files.service,/MAIL_RATE_LIMIT/],["67 idempotency key",files.service,/idempotencyKey/],["68 To supported",files.service,/to: input\.to/],["69 CC supported",files.service,/cc: input\.cc/],["70 BCC supported",files.service,/bcc: input\.bcc/],["71 reply header",files.service,/In-Reply-To/],["72 references header",files.service,/headers\.References/],["73 sent audit",files.service,/mail_message_sent/],["74 draft autosave debounce",files.mailUi,/1500/],["75 draft optimistic version",files.mailApi,/eq\("version"/],["76 draft conflict",files.mailApi,/otra sesión/],["77 attachment private route",files.attachment,/mayAccessThread/],["78 attachment MIME allowlist",files.attachment,/application\/pdf/],["79 attachment max size",files.attachment,/10 \* 1024 \* 1024/],["80 no sniff attachment",files.attachment,/X-Content-Type-Options/],["81 attachment audit",files.attachment,/mail_attachment_accessed/],["82 send attachments",files.service,/providerAttachments/],
 ["83 webhook raw body",files.webhook,/request\.text\(\)/],["84 webhook signature",files.webhook,/resend\.webhooks\.verify/],["85 svix event id",files.webhook,/svix-id/],["86 svix timestamp",files.webhook,/svix-timestamp/],["87 svix signature",files.webhook,/svix-signature/],["88 payload hash",files.webhook,/sha256/],["89 event dedupe",files.webhook,/23505/],["90 replay inconsistency",files.webhook,/Evento inconsistente/],["91 official receiving API",files.webhook,/emails\.receiving\.get/],["92 Message-ID stored",files.webhook,/message_id: received\.data\.message_id/],["93 In-Reply-To threading",files.webhook,/in-reply-to/],["94 References threading",files.webhook,/headers\.references/],["95 conservative no subject merge",files.webhook,/if \(!threadId\).*mail_threads/s],["96 unknown recipient ignored",files.webhook,/ignored: true/],["97 inbound attachments durable",files.webhook,/receiving\.attachments\.list/],["98 received audit",files.webhook,/mail_message_received/],["99 inbound notification",files.webhook,/mail_received/],
 ["100 scripts removed",files.security,/allowedTags/],["101 forms removed",files.security,/allowedTags: \[[^\]]+\]/],["102 javascript scheme blocked",files.security,/allowedSchemes: \["http", "https", "mailto"\]/],["103 safe external links",files.security,/noopener noreferrer/],["104 remote images blocked",files.webhook,/hasRemoteImages/],["105 header injection subject",files.security,/safeSubjectSchema.*\\r\\n/s],["106 recipient validation",files.security,/emailAddressSchema/],["107 body not in audit",files.mailMigration,/safe_metadata/],["108 server-only service",files.service,/server-only/],["109 secret not public",files.webhook,/process\.env\.RESEND_WEBHOOK_SECRET/],["110 webhook error generic",files.webhook,/No pudimos procesar el evento/],
 ["111 RLS enabled all mail",files.mailMigration,/enable row level security/],["112 RLS forced all mail",files.mailMigration,/force row level security/],["113 sales mailbox scope",files.mailMigration,/mail_identity_assignments.*auth\.uid/s],["114 manager supervision scope",files.mailMigration,/owner','admin','manager/],["115 attachment storage private",files.mailMigration,/mail-attachments','mail-attachments',false/],["116 message content limit",files.mailMigration,/body_html.*2000000/s],["117 Manager mail use",readFileSync("src/lib/admin/authorization.ts","utf8"),/manager:.*mail:use/s],["118 Manager supervise",readFileSync("src/lib/admin/authorization.ts","utf8"),/manager:.*mail:supervise/s],["119 Manager denied identities",readFileSync("src/lib/admin/authorization.ts","utf8"),/manager: \[(?![^\]]*mail:manage_identities)/s],["120 sales mail use",readFileSync("src/lib/admin/authorization.ts","utf8"),/sales_agent:.*mail:use/s],
 ["121 mobile mail layout",files.css,/@media \(max-width: 767px\).*kc-mail/s],["122 tablet mail layout",files.css,/@media \(max-width: 1023px\).*kc-mail/s],["123 composer dvh",files.css,/kc-mail-composer.*100dvh/s],["124 mobile folder drawer",files.css,/kc-mail-folders\.is-open/],["125 no full-page table",files.mailUi,/min-w-0/],["126 touch targets",files.mailUi,/min-h-11/],["127 client integration",files.client,/admin\/mail\?compose=1/],["128 lead integration",files.lead,/admin\/mail\?compose=1/],["129 project integration",files.project,/admin\/mail\?compose=1/],["130 module integration",files.module,/admin\/mail\?compose=1/],
 ["131 signature management API",files.settingsApi,/save_signature/],["132 signature ownership",files.settingsApi,/eq\("profile_id", auth\.admin\.uid\)/],["133 signature sanitization",files.settingsApi,/sanitizeMailHtml/],["134 template manager permission",files.settingsApi,/mail:manage_templates/],["135 template audit",files.settingsApi,/mail_template_(created|updated)/],["136 signature composer insertion",files.mailUi,/data-kc-signature/],["137 template safe variables",files.mailUi,/client_name\|business_name\|seller_name\|project_name\|proposal_number\|module_name/],["138 missing variables removed",files.mailUi,/variables\[key\] \|\| ""/],["139 proposal PDF attachment",files.mailUi,/Adjuntar PDF de propuesta/],["140 proposal PDF existing route",files.mailUi,/api\/admin\/add-ons\/proposals/],["141 business context panel",files.mailUi,/Cliente.*Proyecto.*Módulo.*Propuesta/s],["142 signature settings UI",files.settingsUi,/Firma profesional/],["143 template settings UI",files.settingsUi,/Plantillas comerciales/],["144 assigned identity signatures",files.settingsApi,/mail_identity_assignments!inner/],["145 settings has no identity management escalation",files.settingsApi,/mail:use/],
 ["146 draft loader exported",files.service,/export async function loadDraft/],["147 draft loader enforces owner",files.service,/mail_drafts.*eq\("owner_id", admin\.uid\)/s],["148 draft API response",files.mailApi,/selectedDraft: draft/],["149 draft reopen UI",files.mailUi,/openDraft\(item\.id\)/],["150 cursor accepted by page",readFileSync("src/app/admin/mail/page.tsx","utf8"),/cursor\?: string/],["151 cursor pagination control",files.mailUi,/Más conversaciones/],["152 mark unread UI",files.mailUi,/act\("unread"/],["153 restore UI",files.mailUi,/act\("restore"/],["154 assignees active only",files.service,/profiles.*eq\("active", true\).*sales_agent/s],["155 assignment checks thread access",files.mailApi,/assign\.success.*mayAccessThread/s],["156 assignment target validated",files.mailApi,/Responsable inválido/],["157 follow-up creates CRM task",files.mailUi,/Crear tarea/],["158 underline formatting",files.mailUi,/aria-label="Subrayado"/],["159 ordered list formatting",files.mailUi,/aria-label="Lista numerada"/],["160 link formatting",files.mailUi,/aria-label="Enlace"/],["161 quote formatting",files.mailUi,/aria-label="Cita"/],
 ["162 empty composer does not autosave",files.mailUi,/isCompletelyEmpty.*return/s],["163 delete draft schema",files.mailApi,/action: z\.literal\("delete_draft"\)/],["164 delete draft enforces owner",files.mailApi,/mail_drafts.*delete\(\).*eq\("owner_id", auth\.admin\.uid\)/s],["165 discard draft UI",files.mailUi,/Descartar borrador.*Confirmar descarte/s],
 ["166 draft created audit",files.mailApi,/mail_draft_created/],["167 draft updated audit",files.mailApi,/mail_draft_updated/],["168 follow-up audit",files.mailApi,/mail_follow_up_created/],["169 canonical thread state audits",files.mailApi,/mail_thread_archived.*mail_thread_trashed.*mail_thread_restored/s],
 ["170 identity list avoids fragile nested relationship",files.identityApi,/assignmentsByIdentity.*profilesById/s],["171 identity list reports query failures",files.identityApi,/identityResult\.error \|\| assignmentResult\.error \|\| profileResult\.error/],
 ["172 outbound provider events are handled",files.webhook,/email\.delivered.*email\.bounced.*email\.complained/s],["173 signed events use the delivery RPC",files.webhook,/apply_mail_delivery_event/],
 ["174 delivery updates preserve content immutability",files.hardeningMigration,/to_jsonb\(new\).*delivery_status.*delivery_status_at.*provider_event_id.*to_jsonb\(old\)/s],["175 delivery RPC is service-role only",files.hardeningMigration,/revoke all on function public\.apply_mail_delivery_event[\s\S]*grant execute[\s\S]*to service_role/],
 ["176 provider timestamps prevent status regression",files.hardeningMigration,/p_occurred_at >= v_message\.delivery_status_at/],["177 send retries reuse one client request id",files.mailUi,/sendRequestId\.current \|\|[\s\S]*crypto\.randomUUID/],
 ["178 completed send retries return the existing message",files.service,/eq\("client_request_id", input\.requestId\)\.maybeSingle[\s\S]*messageId: completed\.id/],["179 new thread id is stable across retries",files.service,/id: input\.requestId[\s\S]*ignoreDuplicates: true/],
 ["180 mail hardening preserves financial and module notification types",files.hardeningMigration,/payment_due_7_days.*payment_due_3_days.*payment_due_today.*payment_overdue.*payment_received.*module.*mail_received.*mail_assigned.*mail_follow_up/s],
 ["181 billing dashboard aggregates in PostgreSQL with RLS",files.hardeningMigration,/billing_dashboard_summary[\s\S]*security invoker[\s\S]*grant execute[\s\S]*to authenticated/],
 ["182 inbound server may insert a scoped notification",files.notificationPrivilegeMigration,/grant insert on table public\.notifications to service_role/],
 ["183 failed inbound replay resumes the stored message",files.webhook,/resume_partial_event[\s\S]*existingMessage\.data\?\.thread_id/],
 ["184 inbound notification retry is idempotent",files.webhook,/notifications"\)\.upsert[\s\S]*onConflict: "firebase_id"[\s\S]*ignoreDuplicates: true/],
 ["185 inbound audit retry is idempotent",files.webhook,/mail_audit_events"\)\.select\("id"\)[\s\S]*eq\("message_id", messageId\)[\s\S]*if \(!existingAudit\.data\)/],
 ["186 provider Message-ID is retrieved after send",files.service,/resend\.emails\.get\(delivery\.data\.id\)[\s\S]*providerMessageId/],
 ["187 client idempotency is separate from provider Message-ID",files.service,/eq\("client_request_id", input\.requestId\)[\s\S]*client_request_id: input\.requestId/],
 ["188 inbound fallback resolves only official provider IDs",files.webhook,/officialProviderMessageId[\s\S]*replyIds\.includes\(officialMessageId\)/],
 ["189 thread reconciliation is service role only",files.threadingMigration,/auth\.role\(\) <> 'service_role'[\s\S]*grant execute[\s\S]*to service_role/],
 ["190 reconciliation never merges by subject",files.threadingMigration,/never merges by subject/],
 ["191 unresolved processed events are reopened",files.threadingMigration,/thread_reconciliation_pending/],
 ["192 delivery status updates remain narrowly mutable",files.threadingMigration,/auth\.role\(\) = 'service_role'[\s\S]*delivery_status'[\s\S]*provider_event_id/],
 ["193 threading diagnostics are bounded stages only",files.webhook,/resolve_direct_parent[\s\S]*resolve_outbound_candidates[\s\S]*retrieve_provider_message_id[\s\S]*reconcile_provider_parent/],
 ["194 candidate recipient matching is bounded and exact",files.webhook,/includesExactRecipient[\s\S]*limit\(100\)[\s\S]*\.slice\(0, 20\)/],
 ["195 candidate lookup selects bounded address metadata",files.webhook,/select\("provider_email_id,thread_id,to_addresses"\)/],
];
for (const [name, source, pattern] of cases) test(name, () => assert.match(source, pattern));
test("196 candidate lookup avoids fragile JSON URL filters", () => assert.doesNotMatch(files.webhook, /\.contains\("to_addresses"/));

const normalizeCases = [["Kenneth Durón","kennethduron"],[" María López ","marialopez"],["sales+team","salesteam"],["A__B","a__b"],[".hidden.","hidden"],["A B C","abc"]];
for (const [input, expected] of normalizeCases) test(`normalizes local part: ${input}`,()=>assert.equal(normalizeLocalPart(input),expected));
test("suggestions are deterministic and unique",()=>assert.deepEqual(suggestLocalParts("Kenneth Durón"),["kenneth","kennethduron","kduron"]));
test("sanitizer removes scripts",()=>assert.doesNotMatch(sanitizeMailHtml("<p>ok</p><script>alert(1)</script>"),/script|alert/));
test("sanitizer removes event handlers",()=>assert.doesNotMatch(sanitizeMailHtml('<p onclick="x">ok</p>'),/onclick/));
test("sanitizer removes forms",()=>assert.doesNotMatch(sanitizeMailHtml("<form><input></form>"),/form|input/));
test("sanitizer removes iframes",()=>assert.doesNotMatch(sanitizeMailHtml('<iframe src="x"></iframe>'),/iframe/));
test("sanitizer rejects javascript URL",()=>assert.doesNotMatch(sanitizeMailHtml('<a href="javascript:x">x</a>'),/javascript/));
test("reply prefix is idempotent",()=>assert.equal(replySubject("Re: Hola"),"Re: Hola"));
test("reply prefix is added",()=>assert.equal(replySubject("Hola"),"Re: Hola"));
test("forward prefix is idempotent",()=>assert.equal(forwardSubject("Fwd: Hola"),"Fwd: Hola"));
test("forward prefix is added",()=>assert.equal(forwardSubject("Hola"),"Fwd: Hola"));
test("references are bounded",()=>assert.equal(parseHeaderReferences(Array.from({length:60},(_,i)=>`<${i}@x>`).join(" ")).length,50));
test("owner has identity management",()=>assert.ok(defaultPermissionsForRole("owner").includes("mail:manage_identities")));
test("manager cannot manage identities",()=>assert.ok(!defaultPermissionsForRole("manager").includes("mail:manage_identities")));
test("manager can supervise",()=>assert.ok(defaultPermissionsForRole("manager").includes("mail:supervise")));
test("sales agent cannot supervise",()=>assert.ok(!defaultPermissionsForRole("sales_agent").includes("mail:supervise")));
test("migrations send no mail",()=>assert.doesNotMatch(files.profileMigration+files.mailMigration,/net\.http_post|resend\.emails\.send/i));
test("migrations run no cron",()=>assert.doesNotMatch(files.profileMigration+files.mailMigration,/cron\.schedule/i));
test("migrations create no fake business mail",()=>assert.doesNotMatch(files.mailMigration,/insert into public\.mail_(threads|messages|drafts)\s*\(/i));
test("service role gets explicit mail privileges without anonymous access",()=>{assert.match(files.privilegeMigration,/grant select, insert, update on public\.mail_threads to service_role/);assert.doesNotMatch(files.privilegeMigration,/\bto anon\b/i);});
