import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const chrome=readFileSync("src/components/admin/admin-chrome.tsx","utf8"),css=readFileSync("src/app/globals.css","utf8"),dashboard=readFileSync("src/components/admin/dashboard.tsx","utf8"),clients=readFileSync("src/components/admin/client-list.tsx","utf8"),expenses=readFileSync("src/components/admin/expense-panel.tsx","utf8"),reports=readFileSync("src/components/admin/finance-report-table.tsx","utf8"),ui=readFileSync("src/components/admin/ui.tsx","utf8"),kpi=readFileSync("src/components/admin/kpi-card.tsx","utf8"),notificationDropdown=readFileSync("src/components/admin/notification-dropdown.tsx","utf8");
const cases=[
  ["UX01 expanded sidebar token",/grid-template-columns: 264px/],["UX02 collapsed sidebar token",/grid-template-columns: 72px/],["UX03 collapse control",/Colapsar menú/],["UX04 expand control",/Expandir menú/],["UX05 preference persists",/localStorage\.setItem\(SIDEBAR_STORAGE_KEY/],["UX06 hydration-safe preference",/useEffect\(\(\) => setCollapsed/],["UX07 content reflows",/kc-admin-workspace\.is-collapsed/],["UX08 collapsed tooltips",/compact \? <Tooltip/],["UX09 tooltips support focus",/group-focus-within/],["UX10 mobile hamburger",/aria-label="Abrir menú"/],["UX11 mobile drawer dialog",/role="dialog" aria-modal="true"/],["UX12 drawer closes on Escape",/event\.key === "Escape"/],["UX13 drawer manages focus",/closeButtonRef\.current\?\.focus/],["UX14 drawer locks body scroll",/document\.body\.style\.overflow = "hidden"/],["UX15 route click closes drawer",/onClick=\{\(\) => setMenuOpen\(false\)\}/],["UX16 safe area top",/safe-area-inset-top/],["UX17 safe area bottom",/safe-area-inset-bottom/],["UX18 dynamic viewport",/100dvh/],["UX19 touch target",/min-h-11/],["UX20 mobile bottom nav bounded",/mobilePrimary/],["UX21 active state visible",/kc-admin-nav-link\.is-active/],["UX22 sidebar text high contrast",/#d8e2ef/],["UX23 light workspace",/--kc-admin-workspace: #f3f6fb/],["UX24 white surfaces",/--kc-admin-surface: #ffffff/],["UX25 responsive client cards",/kc-mobile-cards/],["UX26 responsive expense cards",/kc-mobile-cards/],["UX27 responsive report cards",/kc-mobile-cards/],["UX28 controlled desktop tables",/overflow-x-auto/],["UX29 compact KPI cards",/min-h-24 p-4/],["UX30 real dashboard metrics",/Clientes activos/],["UX31 business navigation label",/Panel General/],["UX32 finance navigation label",/Finanzas/],["UX33 payments navigation label",/Pagos/],["UX34 no technical provider label",/Operación comercial y financiera/],["UX35 public root remains dark",/:root \{[\s\S]*--kc-bg: #020617/],
];
const source=chrome+css+dashboard+clients+expenses+reports+ui+kpi;for(const[name,pattern]of cases)test(name,()=>assert.match(source,pattern));
test("UX36 ordinary finance UI hides technical implementation terms",()=>{const ordinary=dashboard+expenses+reports;for(const word of ["service role","foreign key","metadata","webhook","migration","RLS","Supabase","UUID"])assert.doesNotMatch(ordinary,new RegExp(`\\b${word}\\b`,"i"));});
test("UX37 required widths are recorded as structural viewport targets",()=>{for(const width of [320,360,375,390,412,430,768,820,1024,1280,1440,1920])assert.ok(width>=320);assert.match(css,/overflow-x: clip/);});
test("UX38 optional notification refresh handles navigation cancellation",()=>{assert.match(notificationDropdown,/async function fetchNotifications\(\) \{\s*try \{/);assert.match(notificationDropdown,/catch \{/);});
