import Link from "next/link";
import { FileSpreadsheet, SearchX } from "lucide-react";
import { formatSignedMinor } from "@/lib/billing/money";
import type { CommercialClient, CommercialProject } from "@/lib/commercial/types";
import type { AdminMember } from "@/lib/admin/types";
import type { ExpenseCategory, FinanceReportRow, FinanceReportType } from "@/lib/finance/types";
import { financePeriodLabels } from "@/lib/finance/range";

export const reportLabels: Record<FinanceReportType, string> = { collections: "Cobros recibidos", receivables: "Cuentas por cobrar", overdue: "Vencidos", expenses: "Gastos", cash_result: "Resultado de caja", project_sales: "Ventas por proyecto", seller: "Ventas y cobros por vendedor", module_sales: "Ventas de módulos", module_collected: "Cobrado por módulos", module_outstanding: "Pendiente por módulos", module_recurring: "Cargos mensuales de módulos" };
const typeLabels: Record<string, string> = { payment: "Pago recibido", expense: "Gasto", receivable: "Cuenta por cobrar", project_sale: "Venta de proyecto" };
const methodLabels: Record<string, string> = { bank_transfer: "Transferencia", cash: "Efectivo", card: "Tarjeta", paypal: "PayPal", other: "Otro" };

export type ReportFilters = { report: FinanceReportType; period: string; from: string; to: string; currency: "USD"; clientId?: string; projectId?: string; sellerId?: string; paymentMethod?: string; categoryId?: string; page: number };
function params(filters: ReportFilters, extra: Record<string, string> = {}) { const result = new URLSearchParams(); for (const [key, value] of Object.entries({ ...filters, ...extra })) if (value !== undefined && value !== "" && key !== "page") result.set(key, String(value)); if (extra.page || filters.page > 1) result.set("page", String(extra.page || filters.page)); return result.toString(); }

export function FinanceReportFilters({ filters, clients, projects, members, categories, showReport = true }: { filters: ReportFilters; clients: CommercialClient[]; projects: CommercialProject[]; members: AdminMember[]; categories: ExpenseCategory[]; showReport?: boolean }) {
  return <form method="get" className="kc-filter-bar kc-admin-card grid gap-3 p-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
    {showReport ? <label className="grid gap-1 text-xs font-bold text-kc-muted">Reporte<select name="report" defaultValue={filters.report} className="min-h-11 rounded-xl border px-3 text-sm">{Object.entries(reportLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label> : <input type="hidden" name="report" value={filters.report} />}
    <input type="hidden" name="currency" value="USD" />
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Periodo<select name="period" defaultValue={filters.period} className="min-h-11 rounded-xl border px-3 text-sm">{Object.entries(financePeriodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Desde<input name="from" type="date" defaultValue={filters.from} className="min-h-11 rounded-xl border px-3 text-sm" /></label>
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Hasta<input name="to" type="date" defaultValue={filters.to} className="min-h-11 rounded-xl border px-3 text-sm" /></label>
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Cliente<select name="clientId" defaultValue={filters.clientId || ""} className="min-h-11 rounded-xl border px-3 text-sm"><option value="">Todos</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.company || item.name}</option>)}</select></label>
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Proyecto<select name="projectId" defaultValue={filters.projectId || ""} className="min-h-11 rounded-xl border px-3 text-sm"><option value="">Todos</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Vendedor<select name="sellerId" defaultValue={filters.sellerId || ""} className="min-h-11 rounded-xl border px-3 text-sm"><option value="">Todos</option>{members.map((item) => <option key={item.uid} value={item.uid}>{item.name || item.email}</option>)}</select></label>
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Método<select name="paymentMethod" defaultValue={filters.paymentMethod || ""} className="min-h-11 rounded-xl border px-3 text-sm"><option value="">Todos</option>{Object.entries(methodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
    <label className="grid gap-1 text-xs font-bold text-kc-muted">Categoría<select name="categoryId" defaultValue={filters.categoryId || ""} className="min-h-11 rounded-xl border px-3 text-sm"><option value="">Todas</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <button className="min-h-11 self-end rounded-xl bg-blue-600 px-4 text-sm font-black text-white">Aplicar filtros</button>
  </form>;
}

export function FinanceReportTable({ rows, total, page, pageSize, filters, canExport }: { rows: FinanceReportRow[]; total: number; page: number; pageSize: number; filters: ReportFilters; canExport: boolean }) {
  const visibleTotal = rows.reduce((sum, row) => sum + BigInt(row.amountMinor), BigInt(0));
  return <div className="grid gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black text-kc-text">{reportLabels[filters.report]}</h2><p className="text-sm text-kc-muted">{total} registros · Moneda: USD</p></div>{canExport ? <a href={`/api/admin/finance/export?${params(filters)}`} download className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 text-sm font-black text-emerald-800"><FileSpreadsheet size={17} /> Exportar CSV</a> : null}</div>
    {rows.length ? <><div className="kc-mobile-cards grid gap-3 md:hidden">{rows.map((row) => <article key={`${row.recordType}-${row.recordId}`} className="kc-admin-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-kc-text">{row.concept}</p><p className="mt-1 text-sm text-kc-muted">{row.party}</p></div><strong className={BigInt(row.amountMinor) < BigInt(0) ? "text-rose-700" : "text-kc-text"}>{formatSignedMinor(BigInt(row.amountMinor), "USD")}</strong></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-kc-muted">Fecha</dt><dd className="font-bold">{row.occurredOn}</dd></div><div><dt className="text-kc-muted">Tipo</dt><dd className="font-bold">{typeLabels[row.recordType] || row.recordType}</dd></div><div><dt className="text-kc-muted">Proyecto</dt><dd className="font-bold">{row.projectName || "—"}</dd></div><div><dt className="text-kc-muted">Estado</dt><dd className="font-bold">{row.status}</dd></div></dl></article>)}</div>
      <div className="kc-responsive-table hidden overflow-x-auto rounded-2xl border bg-white md:block"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{["Fecha", "Tipo", "Cliente / proveedor", "Concepto", "Proyecto", "Método", "Importe", "Estado"].map((label) => <th key={label} className="px-4 py-3 text-xs font-black uppercase tracking-[.08em] text-kc-muted">{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={`${row.recordType}-${row.recordId}`} className="border-t"><td className="px-4 py-3">{row.occurredOn}</td><td className="px-4 py-3 font-bold">{typeLabels[row.recordType] || row.recordType}</td><td className="px-4 py-3">{row.party}</td><td className="px-4 py-3 font-bold">{row.concept}</td><td className="px-4 py-3">{row.projectName || "—"}</td><td className="px-4 py-3">{methodLabels[row.paymentMethod] || row.paymentMethod || "—"}</td><td className="px-4 py-3 font-black">{formatSignedMinor(BigInt(row.amountMinor), "USD")}</td><td className="px-4 py-3">{row.status}</td></tr>)}</tbody></table></div>
      <span className="w-fit rounded-xl border bg-white px-3 py-2 text-sm"><span className="text-kc-muted">Subtotal visible USD: </span><strong>{formatSignedMinor(visibleTotal, "USD")}</strong></span></> : <div className="kc-admin-card grid min-h-64 place-items-center p-7 text-center"><div><SearchX className="mx-auto text-blue-700" size={34} /><h3 className="mt-4 text-xl font-black">Sin resultados</h3><p className="mt-2 text-sm text-kc-muted">Ajuste los filtros o registre movimientos reales.</p></div></div>}
    <div className="flex items-center justify-between"><p className="text-sm text-kc-muted">Página {page} de {Math.max(1, Math.ceil(total / pageSize))}</p><div className="flex gap-2"><Link aria-disabled={page <= 1} href={`?${params(filters, { page: String(Math.max(1, page - 1)) })}`} className="inline-flex min-h-11 items-center rounded-xl border px-4 text-sm font-black aria-disabled:pointer-events-none aria-disabled:opacity-40">Anterior</Link><Link aria-disabled={page * pageSize >= total} href={`?${params(filters, { page: String(page + 1) })}`} className="inline-flex min-h-11 items-center rounded-xl border px-4 text-sm font-black aria-disabled:pointer-events-none aria-disabled:opacity-40">Siguiente</Link></div></div>
  </div>;
}
