"use client";

import { FileSignature, LayoutTemplate, Loader2, Save, ShieldCheck, Trash2, Upload } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Toast } from "./ui";
import { RichTextEditor } from "./rich-text-editor";

type Identity = { id: string; email: string; display_name: string };
type Signature = { id: string; identity_id: string | null; name: string; body_html: string; logo_url: string | null; is_default: boolean };
type CorporateSignature = { id: string; identity_id: string | null; name: string; body_html: string; logo_url: string | null; version: number };
type Template = { id: string; name: string; subject: string; body_html: string; active: boolean; version: number };
const corporateDefault = `<p><strong>{{USER_NAME}}</strong><br>{{ROLE_OR_TITLE}} | {{COMPANY_NAME}}<br>{{CORPORATE_EMAIL}}<br><a href="https://kencodehn.com">{{COMPANY_WEB}}</a></p>`;

export function MailSettingsManager() {
  const [signatures, setSignatures] = useState<Signature[]>([]); const [corporateSignatures, setCorporateSignatures] = useState<CorporateSignature[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [identities, setIdentities] = useState<Identity[]>([]);
  const [canManageTemplates, setCanManageTemplates] = useState(false); const [canManageCorporate, setCanManageCorporate] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [signatureId, setSignatureId] = useState(""); const [signatureName, setSignatureName] = useState("Firma principal"); const [signatureIdentity, setSignatureIdentity] = useState(""); const [signatureHtml, setSignatureHtml] = useState(""); const [signatureLogo, setSignatureLogo] = useState<string | null>(null);
  const [corporateId, setCorporateId] = useState(""); const [corporateName, setCorporateName] = useState("Firma corporativa Ken Code"); const [corporateIdentity, setCorporateIdentity] = useState(""); const [corporateHtml, setCorporateHtml] = useState(corporateDefault); const [corporateLogo, setCorporateLogo] = useState<string | null>(null);
  const [templateId, setTemplateId] = useState(""); const [templateName, setTemplateName] = useState(""); const [templateSubject, setTemplateSubject] = useState(""); const [templateHtml, setTemplateHtml] = useState("");

  async function load() { const response = await fetch("/api/admin/mail/settings", { cache: "no-store" }); const body = await response.json(); if (!response.ok) return setError(body.error); setSignatures(body.signatures || []); setCorporateSignatures(body.corporateSignatures || []); setTemplates(body.templates || []); setIdentities(body.identities || []); setCanManageTemplates(body.canManageTemplates === true); setCanManageCorporate(body.canManageCorporate === true); }
  useEffect(() => { void load(); }, []);
  async function submit(payload: object, success: string) { setBusy(true); setError(""); setNotice(""); const response = await fetch("/api/admin/mail/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); setBusy(false); if (!response.ok) return setError(body.error || "No pudimos guardar la configuración."); setNotice(success); await load(); }
  async function uploadImage(file: File, scope: "personal" | "corporate") { setBusy(true); setError(""); const form = new FormData(); form.set("scope", scope); form.set("file", file); const response = await fetch("/api/admin/mail/signature-assets", { method: "POST", body: form }); const body = await response.json(); setBusy(false); if (!response.ok) return setError(body.error || "No pudimos cargar la imagen."); if (scope === "corporate") setCorporateLogo(body.url); else setSignatureLogo(body.url); setNotice("Imagen optimizada y lista para guardar."); }
  async function saveSignature(event: FormEvent) { event.preventDefault(); await submit({ action: "save_signature", id: signatureId || undefined, identityId: signatureIdentity || null, name: signatureName, html: signatureHtml, logoUrl: signatureLogo, isDefault: true }, "Firma personal guardada."); setSignatureId(""); }
  async function saveCorporate(event: FormEvent) { event.preventDefault(); await submit({ action: "save_corporate_signature", id: corporateId || undefined, identityId: corporateIdentity || null, name: corporateName, html: corporateHtml, logoUrl: corporateLogo }, "Nueva versión de la firma corporativa publicada."); setCorporateId(""); }
  async function saveTemplate(event: FormEvent) { event.preventDefault(); await submit({ action: "save_template", id: templateId || undefined, name: templateName, subject: templateSubject, html: templateHtml, active: true, locked: true }, "Nueva versión de la plantilla publicada."); setTemplateId(""); setTemplateName(""); setTemplateSubject(""); setTemplateHtml(""); }
  const imageControl = (scope: "personal" | "corporate", url: string | null, clear: () => void) => <div className="grid gap-2 rounded-xl border bg-slate-50 p-3"><span className="text-xs font-bold">Imagen · PNG, JPG o WebP · máximo 500 KB</span>{url ? <div className="flex flex-wrap items-center gap-3"><img src={url} alt="Vista previa de la firma" className="max-h-24 max-w-full rounded-lg object-contain" /><button type="button" onClick={clear} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-rose-200 px-3 text-xs font-bold text-rose-700"><Trash2 size={15} /> Quitar de la próxima versión</button></div> : null}<label className="inline-flex min-h-10 w-fit cursor-pointer items-center gap-2 rounded-xl border bg-white px-3 text-xs font-bold"><Upload size={15} /> {url ? "Reemplazar imagen" : "Cargar imagen"}<input type="file" className="sr-only" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void uploadImage(file, scope); }} /></label></div>;

  return <div className="grid gap-5"><Toast message={error || notice} variant={error ? "error" : "success"} />
    {canManageCorporate ? <section className="kc-admin-card rounded-2xl border p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck size={18} /></span><div><h2 className="font-display text-xl font-black">Firma corporativa protegida</h2><p className="text-sm text-kc-muted">El Owner publica versiones que heredan los usuarios autorizados.</p></div></div>
      <div className="mt-4 flex flex-wrap gap-2">{corporateSignatures.map((item) => <button key={item.id} type="button" onClick={() => { setCorporateId(item.id); setCorporateName(item.name); setCorporateIdentity(item.identity_id || ""); setCorporateHtml(item.body_html); setCorporateLogo(item.logo_url); }} className="rounded-full border px-3 py-1.5 text-xs font-bold">{item.name} · v{item.version}</button>)}</div>
      <form onSubmit={saveCorporate} className="mt-4 grid gap-3 lg:grid-cols-2"><label className="grid gap-1 text-sm font-bold">Nombre<input value={corporateName} onChange={(e) => setCorporateName(e.target.value)} required minLength={2} maxLength={120} className="min-h-11 rounded-xl border px-3" /></label><label className="grid gap-1 text-sm font-bold">Identidad<select value={corporateIdentity} onChange={(e) => setCorporateIdentity(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">Todas las identidades</option>{identities.map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</select></label><div className="lg:col-span-2"><RichTextEditor value={corporateHtml} onChange={setCorporateHtml} label="Contenido corporativo" placeholder="Use las variables aprobadas" required minHeightClassName="min-h-36" /><p className="mt-2 text-xs text-kc-muted">Variables: USER_NAME, ROLE_OR_TITLE, CORPORATE_EMAIL, COMPANY_NAME y COMPANY_WEB.</p></div><div className="lg:col-span-2">{imageControl("corporate", corporateLogo, () => setCorporateLogo(null))}</div><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 font-black text-white lg:col-span-2"><Save size={17} /> Publicar versión corporativa</button></form>
    </section> : null}
    <div className="grid gap-5 xl:grid-cols-2"><section className="kc-admin-card rounded-2xl border p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><FileSignature size={18} /></span><div><h2 className="font-display text-xl font-black">Firma profesional personal</h2><p className="text-sm text-kc-muted">Se combina con la identidad elegida y queda registrada al enviar.</p></div></div>
      <div className="mt-4 flex flex-wrap gap-2">{signatures.map((item) => <button key={item.id} type="button" onClick={() => { setSignatureId(item.id); setSignatureName(item.name); setSignatureIdentity(item.identity_id || ""); setSignatureHtml(item.body_html); setSignatureLogo(item.logo_url); }} className="rounded-full border px-3 py-1.5 text-xs font-bold">{item.name}{item.is_default ? " · predeterminada" : ""}</button>)}</div>
      <form onSubmit={saveSignature} className="mt-4 grid gap-3"><label className="grid gap-1 text-sm font-bold">Nombre<input value={signatureName} onChange={(e) => setSignatureName(e.target.value)} required minLength={2} maxLength={120} className="min-h-11 rounded-xl border px-3" /></label><label className="grid gap-1 text-sm font-bold">Identidad<select value={signatureIdentity} onChange={(e) => setSignatureIdentity(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">Todas mis identidades</option>{identities.map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</select></label><RichTextEditor value={signatureHtml} onChange={setSignatureHtml} label="Contenido personal" placeholder="Nombre, cargo y datos autorizados" required minHeightClassName="min-h-36" />{imageControl("personal", signatureLogo, () => setSignatureLogo(null))}<button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 font-black text-white"><Save size={17} /> Guardar firma</button></form>
    </section><section className="kc-admin-card rounded-2xl border p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><LayoutTemplate size={18} /></span><div><h2 className="font-display text-xl font-black">Plantillas comerciales</h2><p className="text-sm text-kc-muted">Los vendedores usan el contenido publicado sin alterar la marca.</p></div></div>
      <div className="mt-4 flex flex-wrap gap-2">{templates.filter((item) => item.active).map((item) => <button key={item.id} type="button" disabled={!canManageTemplates} onClick={() => { setTemplateId(item.id); setTemplateName(item.name); setTemplateSubject(item.subject); setTemplateHtml(item.body_html); }} className="rounded-full border px-3 py-1.5 text-xs font-bold disabled:opacity-60">{item.name} · v{item.version}</button>)}</div>
      {canManageTemplates ? <form onSubmit={saveTemplate} className="mt-4 grid gap-3"><label className="grid gap-1 text-sm font-bold">Nombre<input value={templateName} onChange={(e) => setTemplateName(e.target.value)} required minLength={2} maxLength={120} className="min-h-11 rounded-xl border px-3" /></label><label className="grid gap-1 text-sm font-bold">Asunto<input value={templateSubject} onChange={(e) => setTemplateSubject(e.target.value)} maxLength={998} className="min-h-11 rounded-xl border px-3" /></label><RichTextEditor value={templateHtml} onChange={setTemplateHtml} label="Contenido de la plantilla" placeholder="Hola, escriba aquí el contenido…" required minHeightClassName="min-h-40" /><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-violet-700 px-4 font-black text-white"><Save size={17} /> Publicar plantilla</button></form> : <p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-kc-muted">Puede usar plantillas aprobadas desde el compositor. El Owner controla su contenido corporativo.</p>}
    </section></div>{busy ? <div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/20"><Loader2 className="animate-spin text-white" /><span className="sr-only">Guardando</span></div> : null}
  </div>;
}
