"use client";

import { FileSignature, LayoutTemplate, Loader2, Save } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Toast } from "./ui";

type Identity = { id: string; email: string; display_name: string };
type Signature = { id: string; identity_id: string | null; name: string; body_html: string; is_default: boolean };
type Template = { id: string; name: string; subject: string; body_html: string; active: boolean };

export function MailSettingsManager() {
  const [signatures, setSignatures] = useState<Signature[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [identities, setIdentities] = useState<Identity[]>([]); const [canManageTemplates, setCanManageTemplates] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [signatureId, setSignatureId] = useState(""); const [signatureName, setSignatureName] = useState("Firma principal"); const [signatureIdentity, setSignatureIdentity] = useState(""); const [signatureHtml, setSignatureHtml] = useState("");
  const [templateId, setTemplateId] = useState(""); const [templateName, setTemplateName] = useState(""); const [templateSubject, setTemplateSubject] = useState(""); const [templateHtml, setTemplateHtml] = useState("");
  async function load() { const response = await fetch("/api/admin/mail/settings", { cache: "no-store" }); const body = await response.json(); if (!response.ok) return setError(body.error); setSignatures(body.signatures); setTemplates(body.templates); setIdentities(body.identities); setCanManageTemplates(body.canManageTemplates); }
  useEffect(() => { void load(); }, []);
  async function submit(payload: object, success: string) { setBusy(true); setError(""); const response = await fetch("/api/admin/mail/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); setBusy(false); if (!response.ok) return setError(body.error); setNotice(success); await load(); }
  async function saveSignature(event: FormEvent) { event.preventDefault(); await submit({ action: "save_signature", id: signatureId || undefined, identityId: signatureIdentity || null, name: signatureName, html: signatureHtml, isDefault: true }, "Firma guardada."); setSignatureId(""); }
  async function saveTemplate(event: FormEvent) { event.preventDefault(); await submit({ action: "save_template", id: templateId || undefined, name: templateName, subject: templateSubject, html: templateHtml, active: true }, "Plantilla guardada."); setTemplateId(""); setTemplateName(""); setTemplateSubject(""); setTemplateHtml(""); }
  return <div className="grid gap-5 xl:grid-cols-2"><Toast message={error || notice} variant={error ? "error" : "success"} />
    <section className="kc-admin-card rounded-2xl border p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><FileSignature size={18} /></span><div><h2 className="font-display text-xl font-black">Firma profesional</h2><p className="text-sm text-kc-muted">Se aplica en el compositor y se limpia antes de guardar.</p></div></div>
      <div className="mt-4 flex flex-wrap gap-2">{signatures.map((item) => <button key={item.id} type="button" onClick={() => { setSignatureId(item.id); setSignatureName(item.name); setSignatureIdentity(item.identity_id || ""); setSignatureHtml(item.body_html); }} className="rounded-full border px-3 py-1.5 text-xs font-bold">{item.name}{item.is_default ? " · predeterminada" : ""}</button>)}</div>
      <form onSubmit={saveSignature} className="mt-4 grid gap-3"><label className="grid gap-1 text-sm font-bold">Nombre<input value={signatureName} onChange={(e) => setSignatureName(e.target.value)} required minLength={2} maxLength={120} className="min-h-11 rounded-xl border px-3" /></label><label className="grid gap-1 text-sm font-bold">Identidad<select value={signatureIdentity} onChange={(e) => setSignatureIdentity(e.target.value)} className="min-h-11 rounded-xl border px-3"><option value="">Todas mis identidades</option>{identities.map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</select></label><label className="grid gap-1 text-sm font-bold">Contenido<textarea value={signatureHtml} onChange={(e) => setSignatureHtml(e.target.value)} required rows={6} placeholder={'<strong>Nombre</strong>\nKen Code\nkencodehn.com'} className="rounded-xl border p-3 font-mono text-sm" /></label><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 font-black text-white"><Save size={17} /> Guardar firma</button></form>
    </section>
    <section className="kc-admin-card rounded-2xl border p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><LayoutTemplate size={18} /></span><div><h2 className="font-display text-xl font-black">Plantillas comerciales</h2><p className="text-sm text-kc-muted">Variables disponibles: client_name, business_name, seller_name, project_name, proposal_number y module_name.</p></div></div>
      <div className="mt-4 flex flex-wrap gap-2">{templates.filter((item) => item.active).map((item) => <button key={item.id} type="button" disabled={!canManageTemplates} onClick={() => { setTemplateId(item.id); setTemplateName(item.name); setTemplateSubject(item.subject); setTemplateHtml(item.body_html); }} className="rounded-full border px-3 py-1.5 text-xs font-bold disabled:opacity-60">{item.name}</button>)}</div>
      {canManageTemplates ? <form onSubmit={saveTemplate} className="mt-4 grid gap-3"><label className="grid gap-1 text-sm font-bold">Nombre<input value={templateName} onChange={(e) => setTemplateName(e.target.value)} required minLength={2} maxLength={120} className="min-h-11 rounded-xl border px-3" /></label><label className="grid gap-1 text-sm font-bold">Asunto<input value={templateSubject} onChange={(e) => setTemplateSubject(e.target.value)} maxLength={998} className="min-h-11 rounded-xl border px-3" /></label><label className="grid gap-1 text-sm font-bold">Contenido<textarea value={templateHtml} onChange={(e) => setTemplateHtml(e.target.value)} required rows={7} placeholder="Hola {{client_name}}, …" className="rounded-xl border p-3 font-mono text-sm" /></label><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-violet-700 px-4 font-black text-white"><Save size={17} /> Guardar plantilla</button></form> : <p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-kc-muted">Puede usar las plantillas desde el compositor. Su gestión requiere autorización de Manager, Admin u Owner.</p>}
    </section>
    {busy ? <div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/20"><Loader2 className="animate-spin text-white" /></div> : null}
  </div>;
}
