"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Plus,Puzzle,Search} from "lucide-react";
import {useMemo,useState} from "react";
import type {CommercialClient,CommercialProject} from "@/lib/commercial/types";
import type {ProjectAddOn} from "@/lib/add-ons/types";
import {commercialLabels,workLabels} from "@/lib/add-ons/types";
import {formatMinor} from "@/lib/billing/money";

async function create(payload:Record<string,unknown>){const response=await fetch("/api/admin/add-ons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"module_create",payload})});const body=await response.json();if(!response.ok)throw new Error(body.error||"No se pudo crear el modulo.");return body.result as {id:string};}
export function ModuleList({items,clients,projects,canCreate}:{items:ProjectAddOn[];clients:CommercialClient[];projects:Array<CommercialProject&{clientName:string}>;canCreate:boolean}){
 const router=useRouter(),[open,setOpen]=useState(false),[clientId,setClientId]=useState(""),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState("");
 const available=useMemo(()=>projects.filter(project=>!clientId||project.clientId===clientId),[projects,clientId]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setFeedback("");const data=new FormData(event.currentTarget);try{const result=await create({clientId:String(data.get("clientId")),projectId:String(data.get("projectId")),name:String(data.get("name")),description:String(data.get("description")),requestDate:String(data.get("requestDate")),requestedByClient:data.get("requestedByClient")==="on",currency:"USD",notes:String(data.get("notes"))});router.push(`/admin/modulos/${result.id}`);}catch(error){setFeedback(error instanceof Error?error.message:"No se pudo crear.");}finally{setSaving(false);}}
 return <div className="grid gap-5">
  <div className="kc-page-header flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-700">Ventas adicionales</p><h1 className="mt-1 font-display text-3xl font-black text-kc-text">Modulos y ampliaciones</h1><p className="mt-1 max-w-3xl text-sm text-kc-muted">Solicitudes, propuestas versionadas, planes de pago y entrega sin alterar el precio original del proyecto.</p></div>{canCreate?<button onClick={()=>setOpen(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 font-black text-white"><Plus size={18}/> Nuevo modulo</button>:null}</div>
  <form className="kc-admin-card flex flex-col gap-3 p-3 sm:flex-row" role="search"><label className="relative min-w-0 flex-1"><span className="sr-only">Buscar modulos</span><Search className="absolute left-3 top-3.5 text-slate-400" size={17}/><input name="q" placeholder="Buscar por nombre" className="min-h-11 w-full rounded-xl border pl-10 pr-3"/></label><select name="commercialStatus" aria-label="Estado comercial" className="min-h-11 rounded-xl border px-3"><option value="">Todos los estados</option>{Object.entries(commercialLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="min-h-11 rounded-xl border px-5 font-black">Filtrar</button></form>
  {items.length?<div className="grid gap-3"><div className="hidden overflow-hidden rounded-2xl border bg-white md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Modulo</th><th className="p-4">Cliente / proyecto</th><th className="p-4">Comercial</th><th className="p-4">Desarrollo</th><th className="p-4 text-right">Venta adicional</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t"><td className="p-4"><Link href={`/admin/modulos/${item.id}`} className="font-black text-blue-700">{item.name}</Link></td><td className="p-4"><strong>{item.clientName}</strong><span className="block text-xs text-kc-muted">{item.projectName}</span></td><td className="p-4">{commercialLabels[item.commercialStatus]}</td><td className="p-4">{workLabels[item.workStatus]}</td><td className="p-4 text-right font-black">{item.acceptedAmountMinor?formatMinor(item.acceptedAmountMinor,"USD"):"Por definir"}</td></tr>)}</tbody></table></div><div className="grid gap-3 md:hidden">{items.map(item=><Link key={item.id} href={`/admin/modulos/${item.id}`} className="kc-admin-card p-4"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700"><Puzzle size={20}/></span><div className="min-w-0"><h2 className="font-black">{item.name}</h2><p className="truncate text-sm text-kc-muted">{item.clientName} · {item.projectName}</p></div></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-kc-muted">Comercial</dt><dd className="font-bold">{commercialLabels[item.commercialStatus]}</dd></div><div><dt className="text-kc-muted">Desarrollo</dt><dd className="font-bold">{workLabels[item.workStatus]}</dd></div></dl></Link>)}</div></div>:<div className="kc-admin-card grid min-h-64 place-items-center p-8 text-center"><div><Puzzle className="mx-auto text-blue-600" size={36}/><h2 className="mt-4 text-2xl font-black">Sin modulos registrados</h2><p className="mt-2 text-sm text-kc-muted">Crea una ampliacion cuando un cliente solicite trabajo fuera del alcance original.</p></div></div>}
  {open?<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/55 p-3"><form onSubmit={submit} role="dialog" aria-modal="true" aria-label="Nuevo modulo" className="kc-modal-viewport w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5"><h2 className="text-2xl font-black">Nuevo modulo o ampliacion</h2><p className="mt-1 text-sm text-kc-muted">La moneda es USD y el precio original del proyecto permanece intacto.</p>{feedback?<p role="alert" className="mt-3 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{feedback}</p>:null}<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Cliente<select name="clientId" value={clientId} onChange={e=>setClientId(e.target.value)} required className="min-h-11 rounded-xl border px-3"><option value="">Seleccione</option>{clients.map(client=><option key={client.id} value={client.id}>{client.company||client.name}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Proyecto<select name="projectId" required className="min-h-11 rounded-xl border px-3"><option value="">Seleccione</option>{available.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Nombre<input name="name" minLength={2} maxLength={180} required className="min-h-11 rounded-xl border px-3"/></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Descripcion<textarea name="description" rows={4} className="rounded-xl border p-3"/></label><label className="grid gap-2 text-sm font-bold">Fecha de solicitud<input name="requestDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required className="min-h-11 rounded-xl border px-3"/></label><label className="flex min-h-11 items-center gap-3 text-sm font-bold"><input name="requestedByClient" type="checkbox" defaultChecked className="h-5 w-5"/> Solicitado por el cliente</label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Notas internas<textarea name="notes" rows={3} className="rounded-xl border p-3"/></label></div><div className="mt-5 grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>setOpen(false)} className="min-h-11 rounded-xl border font-black">Cancelar</button><button disabled={saving} className="min-h-11 rounded-xl bg-blue-600 font-black text-white disabled:opacity-50">{saving?"Guardando...":"Crear modulo"}</button></div></form></div>:null}
 </div>;
}
