import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {createClient,type SupabaseClient} from "@supabase/supabase-js";

const localStatus=process.env.SUPABASE_LOCAL_URL?null:JSON.parse(execFileSync("cmd.exe",["/d","/s","/c","npx.cmd supabase status --output json"],{encoding:"utf8",stdio:["ignore","pipe","ignore"]}));
const url=process.env.SUPABASE_LOCAL_URL||localStatus?.API_URL||"",publishable=process.env.SUPABASE_LOCAL_PUBLISHABLE_KEY||localStatus?.PUBLISHABLE_KEY||"",secret=process.env.SUPABASE_LOCAL_SERVICE_KEY||localStatus?.SECRET_KEY||"";
const parsed=new URL(url);if(!publishable||!secret||!["127.0.0.1","localhost"].includes(parsed.hostname))throw new Error("Historical E2E refuses non-loopback services.");
const service=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),password="Historical-Local-Only-2026!";
const people=[
 {id:"59000000-0000-4000-8000-000000000001",email:"owner.history@example.test",role:"owner",active:true},
 {id:"59000000-0000-4000-8000-000000000002",email:"admin.history@example.test",role:"admin",active:true},
 {id:"59000000-0000-4000-8000-000000000003",email:"sales.history@example.test",role:"sales_agent",active:true},
 {id:"59000000-0000-4000-8000-000000000004",email:"inactive.history@example.test",role:"admin",active:false},
] as const;
for(const person of people){const{error}=await service.auth.admin.createUser({id:person.id,email:person.email,password,email_confirm:true});if(error&&error.status!==422)throw error;}
const now=new Date().toISOString();const profiles=await service.from("profiles").upsert(people.map(person=>({id:person.id,name:`Historical ${person.role}`,email:person.email,role:person.role,active:person.active,created_at:now,updated_at:now})));if(profiles.error)throw profiles.error;
async function login(person:typeof people[number]){const client=createClient(url,publishable,{auth:{persistSession:false,autoRefreshToken:false}});const{error}=await client.auth.signInWithPassword({email:person.email,password});if(error)throw error;return client;}
async function commercial(client:SupabaseClient,operation:string,payload:Record<string,unknown>){return client.rpc("commercial_write",{p_operation:operation,p_payload:payload});}
const owner=await login(people[0]),admin=await login(people[1]),sales=await login(people[2]),inactive=await login(people[3]);
const clientResult=await commercial(owner,"client_create",{name:"Cliente histórico local",company:"Histórico local",clientSince:"2025-06-01",assignedToUid:people[2].id});if(clientResult.error)throw clientResult.error;const clientId=clientResult.data.id;
assert.ok((await sales.rpc("historical_import_start",{p_client_id:clientId})).error);assert.ok((await inactive.rpc("historical_import_start",{p_client_id:clientId})).error);
const started=await owner.rpc("historical_import_start",{p_client_id:clientId});if(started.error)throw started.error;const sessionId=started.data.id;assert.equal(started.data.remindersPaused,true);
const paused=await owner.from("clients").select("billing_notifications_enabled").eq("id",clientId).single();assert.equal(paused.data?.billing_notifications_enabled,false);
const projectResult=await commercial(owner,"project_create",{clientId,name:"Proyecto histórico",status:"completed",totalAmountMinor:"149900",currency:"USD",soldAt:"2025-05-15",effectiveDate:"2025-05-15",startDate:"2025-05-15",assignedToUid:people[2].id});if(projectResult.error)throw projectResult.error;const projectId=projectResult.data.id;
const plan=await commercial(owner,"payment_plan_save",{projectId,name:"Plan histórico",installments:[{label:"Anticipo",amountMinor:"75000",currency:"USD",dueDate:"2025-05-15",dueTime:"09:00"},{label:"Pago final",amountMinor:"74900",currency:"USD",dueDate:"2025-06-15",dueTime:"09:00"}]});if(plan.error)throw plan.error;const activated=await commercial(owner,"payment_plan_activate",{id:plan.data.id});if(activated.error)throw activated.error;
const projectReceivables=await owner.from("receivables").select("id,amount_due_minor,balance_minor").eq("project_id",projectId).eq("origin_type","project_installment").order("due_date");if(projectReceivables.error)throw projectReceivables.error;assert.equal(projectReceivables.data.length,2);
const addOn=await owner.rpc("historical_add_on_create",{p_payload:{sessionId,clientId,projectId,name:"Módulo histórico",description:"Módulo vendido antes del CRM",requestDate:"2025-07-01",effectiveDate:"2025-07-15",amountMinor:"67400",currency:"USD",requestedByClient:true,paymentTerms:"Dos cuotas",workStatus:"delivered",actualDeliveryDate:"2025-08-15",deliveryNotes:"Entregado",monthlyAddOnMinor:"3900",monthlyStartDate:"2025-09-01",monthlyBillingDay:1,monthlyBillingTime:"09:00",installments:[{sequence:1,label:"Cuota 1",amountMinor:"33700",currency:"USD",dueDate:"2025-07-15",dueTime:"09:00",notes:""},{sequence:2,label:"Cuota 2",amountMinor:"33700",currency:"USD",dueDate:"2025-08-15",dueTime:"09:00",notes:""}]}});if(addOn.error)throw addOn.error;
const sale=await owner.from("add_on_sales").select("effective_date,accepted_amount_minor").eq("id",addOn.data.saleId).single();assert.deepEqual({date:sale.data?.effective_date,amount:String(sale.data?.accepted_amount_minor)},{date:"2025-07-15",amount:"67400"});
const module=await owner.from("project_add_ons").select("commercial_status,work_status").eq("id",addOn.data.addOnId).single();assert.deepEqual(module.data,{commercial_status:"approved",work_status:"delivered"});
const moduleReceivables=await owner.from("receivables").select("id,amount_due_minor,balance_minor,origin_type").contains("metadata",{addOnId:addOn.data.addOnId}).eq("origin_type","add_on_installment").order("due_date");if(moduleReceivables.error)throw moduleReceivables.error;assert.equal(moduleReceivables.data.length,2);
const payment=await owner.rpc("financial_write",{p_operation:"payment_post",p_payload:{clientId,currency:"USD",amountMinor:"108700",paidAt:"2025-08-15T15:00:00.000Z",method:"bank_transfer",reference:"LOCAL-HISTORY",notes:"Registro histórico local",notifyClient:false,allocations:[{receivableId:projectReceivables.data[0].id,amountMinor:"75000"},{receivableId:moduleReceivables.data[0].id,amountMinor:"33700"}]}});if(payment.error)throw payment.error;
const completed=await owner.rpc("historical_import_complete",{p_session_id:sessionId,p_enable_reminders:false});if(completed.error)throw completed.error;assert.equal(completed.data.remindersEnabled,false);assert.ok(Number(completed.data.skippedReminderEvents)>=1);
const events=await owner.from("billing_reminder_events").select("state,skipped_reason,scheduled_at").in("receivable_id",[...projectReceivables.data,...moduleReceivables.data].map(row=>row.id)).lte("scheduled_at",new Date().toISOString());assert.ok(events.data?.length);assert.ok(events.data?.every(event=>["skipped","superseded"].includes(event.state)));assert.ok(events.data?.some(event=>event.skipped_reason==="historical_import"));
assert.equal((await owner.from("historical_import_sessions").select("id").eq("id",sessionId)).data?.length,1);assert.equal((await admin.from("historical_import_sessions").select("id").eq("id",sessionId)).data?.length,1);assert.equal((await sales.from("historical_import_sessions").select("id").eq("id",sessionId)).data?.length,0);
assert.equal((await service.from("email_logs").select("id",{count:"exact",head:true})).count,0);assert.equal((await service.from("push_logs").select("id",{count:"exact",head:true})).count,0);
console.log(JSON.stringify({target:"loopback-only",session:"PASS",reminders:"PAUSED_AND_OLD_WINDOWS_SKIPPED",project:{sold:"1499.00",installments:2},module:{sold:"674.00",effectiveDate:"2025-07-15",status:"delivered",installments:2},payment:{amount:"1087.00",allocations:2},rls:{owner:"PASS",admin:"PASS",sales:"DENIED",inactive:"DENIED"},deliveries:{email:0,push:0}},null,2));
