import assert from "node:assert/strict";
import { createClient } from "@supabase/supabase-js";

const apiUrl = process.env.SUPABASE_LOCAL_URL || ""; const publishableKey = process.env.SUPABASE_LOCAL_PUBLISHABLE_KEY || ""; const serviceKey = process.env.SUPABASE_LOCAL_SERVICE_KEY || "";
const parsed = new URL(apiUrl); if (!publishableKey || !serviceKey || !["127.0.0.1", "localhost"].includes(parsed.hostname)) throw new Error("Phase 5 E2E refuses non-loopback services.");
const service = createClient(apiUrl, serviceKey, { auth: { persistSession: false, autoRefreshToken: false } }); const password = "Phase5-Local-Only-2026!"; const now = new Date().toISOString(); const runId = crypto.randomUUID().slice(0, 8);
const people = [
  { id: crypto.randomUUID(), email: `owner.${runId}@example.test`, role: "owner", active: true },
  { id: crypto.randomUUID(), email: `manager.${runId}@example.test`, role: "manager", active: true },
  { id: crypto.randomUUID(), email: `sales.a.${runId}@example.test`, role: "sales_agent", active: true },
  { id: crypto.randomUUID(), email: `sales.b.${runId}@example.test`, role: "sales_agent", active: true },
  { id: crypto.randomUUID(), email: `inactive.${runId}@example.test`, role: "sales_agent", active: false },
] as const;
for (const person of people) { const created = await service.auth.admin.createUser({ id: person.id, email: person.email, password, email_confirm: true }); if (created.error && created.error.status !== 422) throw created.error; }
const profiles = await service.from("profiles").upsert(people.map((person) => ({ id: person.id, name: `Phase 5 ${person.role}`, display_name: `Phase 5 ${person.role}`, email: person.email, role: person.role, active: person.active, created_at: now, updated_at: now }))); if (profiles.error) throw profiles.error;
async function login(index: number) { const client = createClient(apiUrl, publishableKey, { auth: { persistSession: false, autoRefreshToken: false } }); const result = await client.auth.signInWithPassword({ email: people[index].email, password }); if (result.error) throw result.error; return client; }
const owner = await login(0), manager = await login(1), salesA = await login(2), salesB = await login(3), inactive = await login(4);

const identities = await service.from("mail_identities").insert([{ local_part: `owner-${runId}`, display_name: "Owner Local", created_by: people[0].id }, { local_part: `sales-${runId}`, display_name: "Sales Local", created_by: people[0].id }, { local_part: `other-${runId}`, display_name: "Other Local", created_by: people[0].id }]).select("id,email"); if (identities.error) throw identities.error;
const [ownerIdentity, salesIdentity, otherIdentity] = identities.data; const assignments = await service.from("mail_identity_assignments").insert([{ identity_id: ownerIdentity.id, profile_id: people[0].id, is_primary: true, assigned_by: people[0].id }, { identity_id: salesIdentity.id, profile_id: people[2].id, is_primary: true, assigned_by: people[0].id }, { identity_id: otherIdentity.id, profile_id: people[3].id, is_primary: true, assigned_by: people[0].id }]); if (assignments.error) throw assignments.error;
const threads = await service.from("mail_threads").insert([{ identity_id: salesIdentity.id, subject: "Thread A", assigned_to: people[2].id, created_by: people[2].id }, { identity_id: otherIdentity.id, subject: "Thread B", assigned_to: people[3].id, created_by: people[3].id }]).select("id"); if (threads.error) throw threads.error; const [threadA, threadB] = threads.data;
const message = await service.from("mail_messages").insert({ thread_id: threadA.id, direction: "outbound", delivery_status: "sent", provider_email_id: `phase5-local-outbound-${runId}`, message_id: `<phase5-local-${runId}@example.test>`, from_address: { email: salesIdentity.email }, to_addresses: [{ email: "client@example.test" }], subject: "Thread A", body_html: "<p>Sanitized local fixture</p>", body_text: "Sanitized local fixture", sent_by: people[2].id, sender_identity_id: salesIdentity.id, sender_snapshot: { userId: people[2].id, email: people[2].email }, sent_at: now }).select("id,sender_snapshot").single(); if (message.error) throw message.error;
const fixtureThreadIds = [threadA.id, threadB.id]; assert.equal((await owner.from("mail_threads").select("id").in("id", fixtureThreadIds)).data?.length, 2); assert.equal((await manager.from("mail_threads").select("id").in("id", fixtureThreadIds)).data?.length, 2); assert.deepEqual((await salesA.from("mail_threads").select("id").in("id", fixtureThreadIds)).data?.map((row) => row.id), [threadA.id]); assert.deepEqual((await salesB.from("mail_threads").select("id").in("id", fixtureThreadIds)).data?.map((row) => row.id), [threadB.id]); assert.equal((await inactive.from("mail_threads").select("id").in("id", fixtureThreadIds)).data?.length, 0);
assert.ok((await service.from("mail_messages").update({ subject: "Mutated" }).eq("id", message.data.id)).error, "Delivered content must be immutable");
const deliveryBase = Date.now() + 60_000;
const delivered = await service.rpc("apply_mail_delivery_event", { p_provider_email_id: `phase5-local-outbound-${runId}`, p_provider_event_id: `evt_delivered_${runId}`, p_status: "delivered", p_occurred_at: new Date(deliveryBase + 60_000).toISOString() }); if (delivered.error) throw delivered.error; assert.equal(delivered.data?.[0]?.applied, true);
const staleDelayed = await service.rpc("apply_mail_delivery_event", { p_provider_email_id: `phase5-local-outbound-${runId}`, p_provider_event_id: `evt_delayed_${runId}`, p_status: "delayed", p_occurred_at: new Date(deliveryBase).toISOString() }); if (staleDelayed.error) throw staleDelayed.error; assert.equal(staleDelayed.data?.[0]?.applied, false);
const deliveryState = await service.from("mail_messages").select("delivery_status,provider_event_id,subject").eq("id", message.data.id).single(); assert.deepEqual(deliveryState.data, { delivery_status: "delivered", provider_event_id: `evt_delivered_${runId}`, subject: "Thread A" });
const draft = await service.from("mail_drafts").insert({ owner_id: people[2].id, identity_id: salesIdentity.id, subject: "Autosaved", body_text: "Draft", body_html: "<p>Draft</p>" }).select("id").single(); if (draft.error) throw draft.error; assert.equal((await salesA.from("mail_drafts").select("id")).data?.length, 1); assert.equal((await salesB.from("mail_drafts").select("id")).data?.length, 0);
const eventId = `evt_phase5_local_${runId}`; const firstEvent = await service.from("mail_webhook_events").insert({ provider_event_id: eventId, event_type: "email.received", payload_hash: "hash" }); assert.equal(firstEvent.error, null); assert.equal((await service.from("mail_webhook_events").insert({ provider_event_id: eventId, event_type: "email.received", payload_hash: "hash" })).error?.code, "23505");
const unassign = await service.from("mail_identity_assignments").update({ active: false, is_primary: false, unassigned_at: now }).eq("identity_id", salesIdentity.id).eq("profile_id", people[2].id); if (unassign.error) throw unassign.error; const reassign = await service.from("mail_identity_assignments").insert({ identity_id: salesIdentity.id, profile_id: people[3].id, is_primary: false, assigned_by: people[0].id }); if (reassign.error) throw reassign.error; await service.from("mail_threads").update({ assigned_to: people[3].id }).eq("id", threadA.id);
assert.equal((await salesA.from("mail_threads").select("id").eq("id", threadA.id)).data?.length, 0); assert.equal((await salesB.from("mail_threads").select("id").eq("id", threadA.id)).data?.length, 1); const preserved = await service.from("mail_messages").select("sender_snapshot").eq("id", message.data.id).single(); assert.equal(preserved.data?.sender_snapshot.userId, people[2].id);
assert.equal((await service.from("email_logs").select("id", { count: "exact", head: true })).count, 0); assert.equal((await service.from("push_logs").select("id", { count: "exact", head: true })).count, 0);
console.log(JSON.stringify({ target: "loopback-only", outbound: "PASS", deliveryEvents: { delivered: "PASS", outOfOrderIgnored: "PASS", contentImmutable: "PASS" }, inboundFixture: "PASS", threading: "PASS", draftRecovery: "PASS", immutableMessages: "PASS", webhookDedupe: "PASS", reassignment: { futureAccess: "PASS", historyPreserved: "PASS", formerUserDenied: "PASS" }, rls: { owner: "PASS", manager: "PASS", salesOwn: "PASS", salesOther: "DENIED", inactive: "DENIED" }, externalDeliveries: { email: 0, push: 0 } }, null, 2));
