import assert from "node:assert/strict";
import {createClient,type SupabaseClient} from "@supabase/supabase-js";
type Local={API_URL:string;PUBLISHABLE_KEY:string;SECRET_KEY:string};
function localStatus():Local{const value={API_URL:process.env.SUPABASE_LOCAL_URL,PUBLISHABLE_KEY:process.env.SUPABASE_LOCAL_PUBLISHABLE_KEY,SECRET_KEY:process.env.SUPABASE_LOCAL_SERVICE_KEY} as Local;const parsed=new URL(value.API_URL);if(!value.PUBLISHABLE_KEY||!value.SECRET_KEY||!["127.0.0.1","localhost"].includes(parsed.hostname))throw new Error("Phase 4 E2E refuses non-loopback services.");return value;}
const local=localStatus(),service=createClient(local.API_URL,local.SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),password="Phase4-Local-Only-2026!";
const people=[{id:"54000000-0000-4000-8000-000000000001",email:"owner.phase4@example.test",role:"owner",active:true},{id:"54000000-0000-4000-8000-000000000002",email:"sales.phase4@example.test",role:"sales_agent",active:true},{id:"54000000-0000-4000-8000-000000000003",email:"other.phase4@example.test",role:"sales_agent",active:true},{id:"54000000-0000-4000-8000-000000000004",email:"inactive.phase4@example.test",role:"admin",active:false}] as const;
for(const p of people){const{error}=await service.auth.admin.createUser({id:p.id,email:p.email,password,email_confirm:true});if(error&&error.status!==422)throw error;}const now=new Date().toISOString();const profile=await service.from("profiles").upsert(people.map(p=>({id:p.id,name:`Phase 4 ${p.role}`,email:p.email,role:p.role,active:p.active,created_at:now,updated_at:now})));if(profile.error)throw profile.error;
async function auth(person:typeof people[number]){const client=createClient(local.API_URL,local.PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const{error}=await client.auth.signInWithPassword({email:person.email,password});if(error)throw error;return client;}
async function rpc(client:SupabaseClient,name:string,operation:string,payload:Record<string,unknown>){return client.rpc(name,{p_operation:operation,p_payload:payload});}
const owner=await auth(people[0]),sales=await auth(people[1]),other=await auth(people[2]),inactive=await auth(people[3]);
const c=await rpc(owner,"commercial_write","client_create",{name:"Example Client",company:"Example Client",clientSince:"2026-08-29",assignedToUid:people[1].id});if(c.error)throw c.error;const clientId=c.data.id;
const p=await rpc(owner,"commercial_write","project_create",{clientId,name:"Website",status:"active",totalAmountMinor:"149900",currency:"USD",soldAt:"2026-08-29",effectiveDate:"2026-08-29",assignedToUid:people[1].id});if(p.error)throw p.error;const projectId=p.data.id;
const base=await rpc(owner,"commercial_write","recurring_service_save",{projectId,name:"Servicio mensual base",monthlyAmountMinor:"11900",currency:"USD",frequency:"monthly",startDate:"2026-09-01",billingDay:15,billingTime:"09:00",timezone:"America/Tegucigalpa",status:"active"});if(base.error)throw base.error;
const module1=await rpc(owner,"add_on_write","module_create",{clientId,projectId,name:"Accounting Module",description:"Accounting extension",requestDate:"2026-08-29",requestedByClient:true,currency:"USD",sellerId:people[1].id,notes:"local fixture"});if(module1.error)throw module1.error;
const v1=await rpc(owner,"add_on_write","proposal_create",{addOnId:module1.data.id,title:"Accounting Module",scope:"Accounting scope v1",amountMinor:"80000",currency:"USD",paymentTerms:"Custom",monthlyAddOnMinor:"0",estimatedDelivery:"4 weeks",validUntil:"2026-10-01",clientNotes:"Client note",internalNotes:"PRIVATE INTERNAL NOTE"});if(v1.error)throw v1.error;
const v2=await rpc(owner,"add_on_write","proposal_create",{addOnId:module1.data.id,title:"Accounting Module",scope:"Negotiated accounting scope",amountMinor:"67400",currency:"USD",paymentTerms:"Two installments",monthlyAddOnMinor:"0",estimatedDelivery:"4 weeks",validUntil:"2026-10-01",clientNotes:"Final client note",internalNotes:"private local"});if(v2.error)throw v2.error;
if((await rpc(owner,"add_on_write","proposal_mark_sent",{proposalId:v2.data.id})).error)throw new Error("mark sent failed");const accepted=await rpc(owner,"add_on_write","proposal_accept",{proposalId:v2.data.id,effectiveDate:"2026-08-29",decisionNotes:"Accepted locally"});if(accepted.error)throw accepted.error;
const plan=await rpc(owner,"add_on_write","payment_plan_save",{saleId:accepted.data.saleId,name:"Two payments",currency:"USD",installments:[{sequence:1,label:"Cuota 1",amountMinor:"33700",currency:"USD",dueDate:"2026-09-15",dueTime:"09:00",notes:""},{sequence:2,label:"Cuota 2",amountMinor:"33700",currency:"USD",dueDate:"2026-09-30",dueTime:"09:00",notes:""}]});if(plan.error)throw plan.error;if((await rpc(owner,"add_on_write","payment_plan_activate",{planId:plan.data.id})).error)throw new Error("activation failed");
const rec=await owner.from("receivables").select("id,amount_due_minor,balance_minor,origin_type").eq("project_id",projectId).eq("origin_type","add_on_installment").order("due_date");if(rec.error)throw rec.error;assert.equal(rec.data.length,2);assert.ok(rec.data.every(row=>String(row.amount_due_minor)==="33700"&&row.origin_type==="add_on_installment"));
const payment=await rpc(owner,"financial_write","payment_post",{clientId,currency:"USD",amountMinor:"33700",paidAt:"2026-09-15T15:00:00.000Z",method:"bank_transfer",reference:"LOCAL-P4",notes:"",notifyClient:false,allocations:[{receivableId:rec.data[0].id,amountMinor:"33700"}]});if(payment.error)throw payment.error;
const balances=await owner.from("receivables").select("balance_minor").in("id",rec.data.map(row=>row.id)).order("due_date");assert.deepEqual(balances.data?.map(row=>String(row.balance_minor)),["0","33700"]);
const project=await owner.from("projects").select("total_amount_minor").eq("id",projectId).single();assert.equal(String(project.data?.total_amount_minor),"149900");const history=await owner.from("add_on_proposals").select("version,status,amount_minor").eq("add_on_id",module1.data.id).order("version");if(history.error)throw history.error;assert.deepEqual(history.data?.map(row=>[row.version,row.status,String(row.amount_minor)]),[[1,"superseded","80000"],[2,"accepted","67400"]]);
const summary=await owner.rpc("finance_add_on_summary",{p_from:"2026-01-01",p_to:"2026-12-31"});if(summary.error)throw summary.error;assert.deepEqual([String(summary.data[0].original_project_sales_minor),String(summary.data[0].add_on_sales_minor),String(summary.data[0].lifetime_sold_minor),String(summary.data[0].add_on_collected_minor),String(summary.data[0].add_on_outstanding_minor)],["149900","67400","217300","33700","33700"]);
const ai=await rpc(owner,"add_on_write","module_create",{clientId,projectId,name:"AI Module",description:"AI extension",requestDate:"2026-08-29",requestedByClient:true,currency:"USD",sellerId:people[1].id,notes:""});if(ai.error)throw ai.error;const aiProposal=await rpc(owner,"add_on_write","proposal_create",{addOnId:ai.data.id,title:"AI Module",scope:"AI implementation",amountMinor:"40000",currency:"USD",paymentTerms:"One payment",monthlyAddOnMinor:"3900",estimatedDelivery:"2 weeks",validUntil:"",clientNotes:"",internalNotes:""});if(aiProposal.error)throw aiProposal.error;await rpc(owner,"add_on_write","proposal_mark_sent",{proposalId:aiProposal.data.id});const aiAccepted=await rpc(owner,"add_on_write","proposal_accept",{proposalId:aiProposal.data.id,effectiveDate:"2026-08-29",decisionNotes:"accepted"});if(aiAccepted.error)throw aiAccepted.error;const recurring=await rpc(owner,"add_on_write","recurring_configure",{saleId:aiAccepted.data.saleId,name:"AI adicional",monthlyAmountMinor:"3900",currency:"USD",startDate:"2026-09-01",billingDay:15,billingTime:"09:00",status:"active"});if(recurring.error)throw recurring.error;const monthly=await owner.from("add_on_recurring_services").select("monthly_amount_minor").eq("id",recurring.data.id).single();assert.equal(BigInt(monthly.data!.monthly_amount_minor)+BigInt(11900),BigInt(15800));
const rejected=await rpc(owner,"add_on_write","module_create",{clientId,projectId,name:"Rejected Module",description:"Rejected",requestDate:"2026-08-29",requestedByClient:true,currency:"USD",notes:""});const rejectedProposal=await rpc(owner,"add_on_write","proposal_create",{addOnId:rejected.data.id,title:"Rejected Module",scope:"Rejected scope",amountMinor:"10000",currency:"USD",paymentTerms:"",monthlyAddOnMinor:"0",estimatedDelivery:"",validUntil:"",clientNotes:"",internalNotes:""});await rpc(owner,"add_on_write","proposal_reject",{proposalId:rejectedProposal.data.id,decisionNotes:"Not approved"});assert.equal((await owner.from("receivables").select("id",{count:"exact",head:true}).eq("metadata->>addOnId",rejected.data.id)).count,0);
const interval=await rpc(owner,"add_on_write","module_create",{clientId,projectId,name:"15 Day Module",description:"Interval",requestDate:"2026-08-29",requestedByClient:true,currency:"USD",notes:""});const intervalProposal=await rpc(owner,"add_on_write","proposal_create",{addOnId:interval.data.id,title:"15 Day Module",scope:"Interval scope",amountMinor:"60000",currency:"USD",paymentTerms:"15 days",monthlyAddOnMinor:"0",estimatedDelivery:"",validUntil:"",clientNotes:"",internalNotes:""});await rpc(owner,"add_on_write","proposal_mark_sent",{proposalId:intervalProposal.data.id});const intervalSale=await rpc(owner,"add_on_write","proposal_accept",{proposalId:intervalProposal.data.id,effectiveDate:"2026-08-29",decisionNotes:""});const intervalPlan=await rpc(owner,"add_on_write","payment_plan_save",{saleId:intervalSale.data.saleId,name:"15 day plan",currency:"USD",installments:[{sequence:1,label:"Day 1",amountMinor:"30000",currency:"USD",dueDate:"2026-09-01",dueTime:"",notes:""},{sequence:2,label:"Day 16",amountMinor:"30000",currency:"USD",dueDate:"2026-09-16",dueTime:"",notes:""}]});assert.equal(intervalPlan.error,null);
assert.ok((await rpc(owner,"add_on_write","module_create",{clientId,projectId,name:"HNL manipulated",description:"",requestDate:"2026-08-29",requestedByClient:true,currency:"HNL",notes:""})).error);assert.ok((await rpc(owner,"add_on_write","module_create",{clientId,projectId,name:"EUR manipulated",description:"",requestDate:"2026-08-29",requestedByClient:true,currency:"EUR",notes:""})).error);
assert.equal((await sales.from("project_add_ons").select("id")).data?.length,4);assert.equal((await other.from("project_add_ons").select("id")).data?.length,0);assert.equal((await inactive.from("project_add_ons").select("id")).data?.length,0);assert.ok((await sales.rpc("finance_add_on_summary",{p_from:"2026-01-01",p_to:"2026-12-31"})).error);
const emails=await service.from("email_logs").select("id",{count:"exact",head:true}),pushes=await service.from("push_logs").select("id",{count:"exact",head:true});assert.equal(emails.count,0);assert.equal(pushes.count,0);
console.log(JSON.stringify({target:"loopback-only",accounting:{v1:"superseded",v2:"accepted",sale:"674.00",receivables:2,paid:"337.00",outstanding:"337.00"},project:{original:"1499.00",lifetime:"2173.00"},ai:{implementation:"400.00",baseMonthly:"119.00",addOnMonthly:"39.00",combined:"158.00"},fifteenDayPlan:"PASS",rejectedProposal:{receivables:0},currency:{USD:"PASS",HNL:"REJECTED",EUR:"REJECTED"},rls:{owner:"PASS",salesOwn:"PASS",salesOther:"DENIED",inactive:"DENIED"},externalDeliveries:{email:0,push:0}},null,2));


