import {mkdir,writeFile} from "node:fs/promises";
import {createProposalPdf} from "../src/lib/add-ons/proposal-pdf.ts";
import type {AddOnProposal,ProjectAddOn} from "../src/lib/add-ons/types.ts";
const proposal:AddOnProposal={id:"sample",addOnId:"sample",proposalNumber:"KC-2026-000042",version:2,status:"sent",title:"Modulo de contabilidad",scope:"Implementacion de un modulo de contabilidad con catalogo de cuentas, registro de movimientos, estados financieros basicos, permisos por rol y exportacion profesional. Incluye configuracion inicial, pruebas de aceptacion y capacitacion remota.",amountMinor:"67400",currency:"USD",paymentTerms:"Dos cuotas de USD $337.00: la primera al aceptar la propuesta y la segunda en la fecha acordada de entrega.",monthlyAddOnMinor:"3900",estimatedDelivery:"Cuatro semanas desde la aprobacion y recepcion del primer pago.",validUntil:"2026-09-30",clientNotes:"El alcance final se validara en una sesion de inicio con el equipo del cliente.",internalNotes:"ESTO NUNCA DEBE APARECER",createdBy:"sample",sentAt:null,decidedAt:null,decisionNotes:"",createdAt:"2026-08-29T15:00:00.000Z"};
const addOn:ProjectAddOn={id:"sample",projectId:"sample",projectName:"Sitio web corporativo",clientId:"sample",clientName:"Example Client",name:"Modulo de contabilidad",description:"",requestDate:"2026-08-29",requestedByClient:true,commercialStatus:"proposal_sent",workStatus:"pending",quotedAmountMinor:"67400",acceptedAmountMinor:null,currency:"USD",acceptedProposalId:null,sellerId:null,effectiveDate:null,plannedStartDate:null,targetDeliveryDate:null,actualDeliveryDate:null,approvedAt:null,rejectedAt:null,rejectionReason:"",cancelledAt:null,cancellationReason:"",deliveredAt:null,deliveryNotes:"",notes:"",createdAt:"2026-08-29T15:00:00.000Z",updatedAt:"2026-08-29T15:00:00.000Z",proposals:[proposal],sale:null,paymentPlans:[],recurring:null,paidMinor:"0",outstandingMinor:"0"};
await mkdir("output/pdf",{recursive:true});
const bytes=await createProposalPdf({proposal,addOn});
await writeFile("output/pdf/KC-2026-000042-sample.pdf",bytes);
console.log(JSON.stringify({path:"output/pdf/KC-2026-000042-sample.pdf",bytes:bytes.length,internalNoteRendered:false}));
